In [3]:
library(tidyverse)

equivalent **`np.select`**

# A general vectorised if

This function allows you to vectorise multiple `if_else()` statements. It is an R equivalent of the SQL CASE WHEN statement. If no cases match, NA is returned.

```r
case_when(...)
```

# Examples

this work like CASE in SQL

In [5]:
x <- 1:50
res <- case_when(
  x %% 35 == 0 ~ "fizz buzz",
  x %% 5 == 0 ~ "fizz",
  x %% 7 == 0 ~ "buzz",
  TRUE ~ as.character(x)
)

print(res)

 [1] "1"         "2"         "3"         "4"         "fizz"      "6"
 [7] "buzz"      "8"         "9"         "fizz"      "11"        "12"
[13] "13"        "buzz"      "fizz"      "16"        "17"        "18"
[19] "19"        "fizz"      "buzz"      "22"        "23"        "24"
[25] "fizz"      "26"        "27"        "buzz"      "29"        "fizz"
[31] "31"        "32"        "33"        "34"        "fizz buzz" "36"
[37] "37"        "38"        "39"        "fizz"      "41"        "buzz"
[43] "43"        "44"        "fizz"      "46"        "47"        "48"
[49] "buzz"      "fizz"

In [6]:
# Like an if statement, the arguments are evaluated in order, so you must
# proceed from the most specific to the most general. This won't work:
case_when(
  TRUE ~ as.character(x),
  x %%  5 == 0 ~ "fizz",
  x %%  7 == 0 ~ "buzz",
  x %% 35 == 0 ~ "fizz buzz"
)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
[16] "16" "17" "18" "19" "20" "21" "22" "23" "24" "25" "26" "27" "28" "29" "30"
[31] "31" "32" "33" "34" "35" "36" "37" "38" "39" "40" "41" "42" "43" "44" "45"
[46] "46" "47" "48" "49" "50"

In [7]:
# If none of the cases match, NA is used:
case_when(
  x %%  5 == 0 ~ "fizz",
  x %%  7 == 0 ~ "buzz",
  x %% 35 == 0 ~ "fizz buzz"
)

 [1] NA     NA     NA     NA     "fizz" NA     "buzz" NA     NA     "fizz"
[11] NA     NA     NA     "buzz" "fizz" NA     NA     NA     NA     "fizz"
[21] "buzz" NA     NA     NA     "fizz" NA     NA     "buzz" NA     "fizz"
[31] NA     NA     NA     NA     "fizz" NA     NA     NA     NA     "fizz"
[41] NA     "buzz" NA     NA     "fizz" NA     NA     NA     "buzz" "fizz"

In [8]:
# Note that NA values in the vector x do not get special treatment. If you want
# to explicitly handle NA values you can use the `is.na` function:
x[2:4] <- NA_real_
case_when(
  x %% 35 == 0 ~ "fizz buzz",
  x %% 5 == 0 ~ "fizz",
  x %% 7 == 0 ~ "buzz",
  is.na(x) ~ "nope",
  TRUE ~ as.character(x)
)

 [1] "1"         "nope"      "nope"      "nope"      "fizz"      "6"
 [7] "buzz"      "8"         "9"         "fizz"      "11"        "12"
[13] "13"        "buzz"      "fizz"      "16"        "17"        "18"
[19] "19"        "fizz"      "buzz"      "22"        "23"        "24"
[25] "fizz"      "26"        "27"        "buzz"      "29"        "fizz"
[31] "31"        "32"        "33"        "34"        "fizz buzz" "36"
[37] "37"        "38"        "39"        "fizz"      "41"        "buzz"
[43] "43"        "44"        "fizz"      "46"        "47"        "48"
[49] "buzz"      "fizz"

In [11]:
case_when(
  x %% 35 == 0 ~ 35, #numeric
  x %% 5 == 0 ~ 5,   #numeric
  x %% 7 == 0 ~ 7,   #numeric
  TRUE ~ NA_real_ #This must be NA_real_, all return values must have the same type
)

 [1] NA NA NA NA  5 NA  7 NA NA  5 NA NA NA  7  5 NA NA NA NA  5  7 NA NA NA  5
[26] NA NA  7 NA  5 NA NA NA NA 35 NA NA NA NA  5 NA  7 NA NA  5 NA NA NA  7  5

In [12]:
# case_when is particularly useful inside mutate when you want to
# create a new variable that relies on a complex combination of existing
# variables
starwars %>%
  select(name:mass, gender, species) %>%
  mutate(
    type = case_when(
      height > 200 | mass > 200 ~ "large",
      species == "Droid"        ~ "robot",
      TRUE                      ~ "other"
    )
  )

    name                  height mass   gender    species        type
1   Luke Skywalker        172      77.0 masculine Human          other
2   C-3PO                 167      75.0 masculine Droid          robot
3   R2-D2                  96      32.0 masculine Droid          robot
4   Darth Vader           202     136.0 masculine Human          large
5   Leia Organa           150      49.0 feminine  Human          other
6   Owen Lars             178     120.0 masculine Human          other
7   Beru Whitesun lars    165      75.0 feminine  Human          other
8   R5-D4                  97      32.0 masculine Droid          robot
9   Biggs Darklighter     183      84.0 masculine Human          other
10  Obi-Wan Kenobi        182      77.0 masculine Human          other
11  Anakin Skywalker      188      84.0 masculine Human          other
12  Wilhuff Tarkin        180        NA masculine Human          other
13  Chewbacca             228     112.0 masculine Wookiee        large
14  Han Solo              180      80.0 masculine Human          other
15  Greedo                173      74.0 masculine Rodian         other
16  Jabba Desilijic Tiure 175    1358.0 masculine Hutt           large
17  Wedge Antilles        170      77.0 masculine Human          other
18  Jek Tono Porkins      180     110.0 masculine Human          other
19  Yoda                   66      17.0 masculine Yoda's species other
20  Palpatine             170      75.0 masculine Human          other
21  Boba Fett             183      78.2 masculine Human          other
22  IG-88                 200     140.0 masculine Droid          robot
23  Bossk                 190     113.0 masculine Trandoshan     other
24  Lando Calrissian      177      79.0 masculine Human          other
25  Lobot                 175      79.0 masculine Human          other
26  Ackbar                180      83.0 masculine Mon Calamari   other
27  Mon Mothma            150        NA feminine  Human          other
28  Arvel Crynyd           NA        NA masculine Human          other
29  Wicket Systri Warrick  88      20.0 masculine Ewok           other
30  Nien Nunb             160      68.0 masculine Sullustan      other
... ...                   ...    ...    ...       ...            ...
58  Cordé                 157       NA  feminine  Human          other
59  Cliegg Lars           183       NA  masculine Human          other
60  Poggle the Lesser     183     80.0  masculine Geonosian      other
61  Luminara Unduli       170     56.2  feminine  Mirialan       other
62  Barriss Offee         166     50.0  feminine  Mirialan       other
63  Dormé                 165       NA  feminine  Human          other
64  Dooku                 193     80.0  masculine Human          other
65  Bail Prestor Organa   191       NA  masculine Human          other
66  Jango Fett            183     79.0  masculine Human          other
67  Zam Wesell            168     55.0  feminine  Clawdite       other
68  Dexter Jettster       198    102.0  masculine Besalisk       other
69  Lama Su               229     88.0  masculine Kaminoan       large
70  Taun We               213       NA  feminine  Kaminoan       large
71  Jocasta Nu            167       NA  feminine  Human          other
72  Ratts Tyerell          79     15.0  masculine Aleena         other
73  R4-P17                 96       NA  feminine  Droid          robot
74  Wat Tambor            193     48.0  masculine Skakoan        other
75  San Hill              191       NA  masculine Muun           other
76  Shaak Ti              178     57.0  feminine  Togruta        other
77  Grievous              216    159.0  masculine Kaleesh        large
78  Tarfful               234    136.0  masculine Wookiee        large
79  Raymus Antilles       188     79.0  masculine Human          other
80  Sly Moore             178     48.0  NA        NA             other
81  Tion Medon            206     80.0  masculine Pau'an         large
82  Finn                   NA       NA  masculine Human          other
83  Rey                    NA       NA  feminine  Human          other
84  Poe Dameron            NA       NA  masculine Human          other
85  BB8                    NA       NA  masculine Droid          robot
86  Captain Phasma         NA       NA  NA        NA             other
87  Padmé Amidala         165     45.0  feminine  Human          other