<h1><a href = 'https://tidyr.tidyverse.org/articles/pivot.html'>Tutorial</a></h1>

In [1]:
library(tidyverse)

Warning message:
"package 'tidyverse' was built under R version 3.6.3"-- Attaching packages ------------------------------------------------------------------------------- tidyverse 1.3.0 --
v ggplot2 3.3.2     v purrr   0.3.4
v tibble  3.0.4     v dplyr   1.0.2
v tidyr   1.1.2     v stringr 1.4.0
v readr   1.4.0     v forcats 0.5.0
Warning message:
"package 'ggplot2' was built under R version 3.6.3"Warning message:
"package 'tibble' was built under R version 3.6.3"Warning message:
"package 'tidyr' was built under R version 3.6.3"Warning message:
"package 'readr' was built under R version 3.6.3"Warning message:
"package 'purrr' was built under R version 3.6.3"Warning message:
"package 'dplyr' was built under R version 3.6.3"Warning message:
"package 'stringr' was built under R version 3.6.3"Warning message:
"package 'forcats' was built under R version 3.6.3"-- Conflicts ---------------------------------------------------------------------------------- tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()

# Longer

**`pivot_longer()`** makes datasets longer by increasing the number of rows and decreasing the number of columns.

```r
pivot_longer(
  data,
  cols,
  names_to = "name",
  names_prefix = NULL,
  names_sep = NULL,
  names_pattern = NULL,
  names_ptypes = list(),
  names_transform = list(),
  names_repair = "check_unique",
  values_to = "value",
  values_drop_na = FALSE,
  values_ptypes = list(),
  values_transform = list(),
  ...
)
```

### String data in column name

The `relig_income` dataset stores counts based on a survey which (among other things) asked people about their religion and annual income:

In [4]:
relig_income

   religion                <$10k $10-20k $20-30k $30-40k $40-50k $50-75k
1  Agnostic                 27    34       60     81      76      137
2  Atheist                  12    27       37     52      35       70
3  Buddhist                 27    21       30     34      33       58
4  Catholic                418   617      732    670     638     1116
5  Don’t know/refused       15    14       15     11      10       35
6  Evangelical Prot        575   869     1064    982     881     1486
7  Hindu                     1     9        7      9      11       34
8  Historically Black Prot 228   244      236    238     197      223
9  Jehovah's Witness        20    27       24     24      21       30
10 Jewish                   19    19       25     25      30       95
11 Mainline Prot           289   495      619    655     651     1107
12 Mormon                   29    40       48     51      56      112
13 Muslim                    6     7        9     10       9       23
14 Orthodox                 13    17       23     32      32       47
15 Other Christian           9     7       11     13      13       14
16 Other Faiths             20    33       40     46      49       63
17 Other World Religions     5     2        3      4       2        7
18 Unaffiliated            217   299      374    365     341      528
   $75-100k $100-150k >150k Don't know/refused
1  122      109        84     96
2   73       59        74     76
3   62       39        53     54
4  949      792       633   1489
5   21       17        18    116
6  949      723       414   1529
7   47       48        54     37
8  131       81        78    339
9   15       11         6     37
10  69       87       151    162
11 939      753       634   1328
12  85       49        42     69
13  16        8         6     22
14  38       42        46     73
15  18       14        12     18
16  46       40        41     71
17   3        4         4      8
18 407      321       258    597

This dataset contains three variables:

* `religion`, stored in the rows,
* `income` spread across the column names, and
* `count` stored in the cell values.

to tidy it we use **`pivot_longer`**

* The first argument is the dataset to reshape, `relig_income`.

* The second argument describes which columns need to be reshaped. In this case, it’s every column apart from `religion`.

* The `names_to` gives the name of the variable that will be created from the data stored in the column names, i.e. `income`.

* The `values_to` gives the name of the variable that will be created from the data stored in the cell value, i.e. `count`.

In [7]:
relig_income %>%
pivot_longer(cols = !religion, names_to = 'income', values_to = 'count')

    religion              income             count
1   Agnostic              <$10k               27
2   Agnostic              $10-20k             34
3   Agnostic              $20-30k             60
4   Agnostic              $30-40k             81
5   Agnostic              $40-50k             76
6   Agnostic              $50-75k            137
7   Agnostic              $75-100k           122
8   Agnostic              $100-150k          109
9   Agnostic              >150k               84
10  Agnostic              Don't know/refused  96
11  Atheist               <$10k               12
12  Atheist               $10-20k             27
13  Atheist               $20-30k             37
14  Atheist               $30-40k             52
15  Atheist               $40-50k             35
16  Atheist               $50-75k             70
17  Atheist               $75-100k            73
18  Atheist               $100-150k           59
19  Atheist               >150k               74
20  Atheist               Don't know/refused  76
21  Buddhist              <$10k               27
22  Buddhist              $10-20k             21
23  Buddhist              $20-30k             30
24  Buddhist              $30-40k             34
25  Buddhist              $40-50k             33
26  Buddhist              $50-75k             58
27  Buddhist              $75-100k            62
28  Buddhist              $100-150k           39
29  Buddhist              >150k               53
30  Buddhist              Don't know/refused  54
... ...                   ...                ...
151 Other Faiths          <$10k               20
152 Other Faiths          $10-20k             33
153 Other Faiths          $20-30k             40
154 Other Faiths          $30-40k             46
155 Other Faiths          $40-50k             49
156 Other Faiths          $50-75k             63
157 Other Faiths          $75-100k            46
158 Other Faiths          $100-150k           40
159 Other Faiths          >150k               41
160 Other Faiths          Don't know/refused  71
161 Other World Religions <$10k                5
162 Other World Religions $10-20k              2
163 Other World Religions $20-30k              3
164 Other World Religions $30-40k              4
165 Other World Religions $40-50k              2
166 Other World Religions $50-75k              7
167 Other World Religions $75-100k             3
168 Other World Religions $100-150k            4
169 Other World Religions >150k                4
170 Other World Religions Don't know/refused   8
171 Unaffiliated          <$10k              217
172 Unaffiliated          $10-20k            299
173 Unaffiliated          $20-30k            374
174 Unaffiliated          $30-40k            365
175 Unaffiliated          $40-50k            341
176 Unaffiliated          $50-75k            528
177 Unaffiliated          $75-100k           407
178 Unaffiliated          $100-150k          321
179 Unaffiliated          >150k              258
180 Unaffiliated          Don't know/refused 597

Neither the `names_to` nor the `values_to` column exists in `relig_income`, so we provide them as character strings surrounded in quotes.

<hr>

<b style = 'color:red'>SELF UNDERSTANDING</b>

To understand how it works internally, it is best to look at only 1 observation:

In [43]:
income <- relig_income %>% slice(1)
income

  religion <$10k $10-20k $20-30k $30-40k $40-50k $50-75k $75-100k $100-150k
1 Agnostic 27    34      60      81      76      137     122      109
  >150k Don't know/refused
1 84    96

In [45]:
income %>% 
pivot_longer(
    cols = !religion,
    names_to = 'income',
    values_to = 'count'
)

   religion income             count
1  Agnostic <$10k               27
2  Agnostic $10-20k             34
3  Agnostic $20-30k             60
4  Agnostic $30-40k             81
5  Agnostic $40-50k             76
6  Agnostic $50-75k            137
7  Agnostic $75-100k           122
8  Agnostic $100-150k          109
9  Agnostic >150k               84
10 Agnostic Don't know/refused  96

### Numeric data in column names

The `billboard` dataset records the billboard rank of songs in the year 2000. It has a form similar to the `relig_income` data, but the data encoded in the column names is really a number, not a string.

In [6]:
billboard

    artist               track                   date.entered wk1 wk2 wk3 wk4
1   2 Pac                Baby Don't Cry (Keep... 2000-02-26   87  82  72  77
2   2Ge+her              The Hardest Part Of ... 2000-09-02   91  87  92  NA
3   3 Doors Down         Kryptonite              2000-04-08   81  70  68  67
4   3 Doors Down         Loser                   2000-10-21   76  76  72  69
5   504 Boyz             Wobble Wobble           2000-04-15   57  34  25  17
6   98^0                 Give Me Just One Nig... 2000-08-19   51  39  34  26
7   A*Teens              Dancing Queen           2000-07-08   97  97  96  95
8   Aaliyah              I Don't Wanna           2000-01-29   84  62  51  41
9   Aaliyah              Try Again               2000-03-18   59  53  38  28
10  Adams, Yolanda       Open My Heart           2000-08-26   76  76  74  69
11  Adkins, Trace        More                    2000-04-29   84  84  75  73
12  Aguilera, Christina  Come On Over Baby (A... 2000-08-05   57  47  45  29
13  Aguilera, Christina  I Turn To You           2000-04-15   50  39  30  28
14  Aguilera, Christina  What A Girl Wants       1999-11-27   71  51  28  18
15  Alice Deejay         Better Off Alone        2000-04-08   79  65  53  48
16  Allan, Gary          Smoke Rings In The D... 2000-01-22   80  78  76  77
17  Amber                Sexual                  1999-07-17   99  99  96  96
18  Anastacia            I'm Outta Love          2000-04-01   92  NA  NA  95
19  Anthony, Marc        My Baby You             2000-09-16   82  76  76  70
20  Anthony, Marc        You Sang To Me          2000-02-26   77  54  50  43
21  Avant                My First Love           2000-11-04   70  62  56  43
22  Avant                Separated               2000-04-29   62  32  30  23
23  BBMak                Back Here               2000-04-29   99  86  60  52
24  Backstreet Boys, The Shape Of My Heart       2000-10-14   39  25  24  15
25  Backstreet Boys, The Show Me The Meaning ... 2000-01-01   74  62  55  25
26  Backstreet Boys, The The One                 2000-05-27   58  50  43  37
27  Badu, Erkyah         Bag Lady                2000-08-19   67  53  42  41
28  Baha Men             Who Let The Dogs Out    2000-07-22   99  92  85  76
29  Barenaked Ladies     Pinch Me                2000-09-09   77  76  69  45
30  Beenie Man           Girls Dem Sugar         2000-10-21   72  72  63  56
... ...                  ...                     ...          ... ... ... ...
288 Thomas, Carl         Emotional               2000-11-25   77  63  61   58
289 Thomas, Carl         I Wish                  2000-03-25   75  64  48   39
290 Thomas, Carl         Summer Rain             2000-09-23   82  82  86   80
291 Tippin, Aaron        Kiss This               2000-08-26   74  72  66   53
292 Train                Meet Virginia           1999-10-09   76  67  59   54
293 Trick Daddy          Shut Up                 2000-05-20   99  95  87   87
294 Trina                Pull Over               2000-09-09   97  93  96  100
295 Tritt, Travis        Best Of Intentions      2000-08-19   97  86  79   70
296 Tuesday              I Know                  2000-12-30   98  98  NA   NA
297 Urban, Keith         Your Everything         2000-07-15   81  80  73   73
298 Usher                Pop Ya Collar           2000-11-04   68  64  60   60
299 Vassar, Phil         Carlene                 2000-03-04   75  67  64   64
300 Vassar, Phil         Just Another Day In ... 2000-09-30   81  81  76   67
301 Vertical Horizon     Everything You Want     2000-01-22   70  61  53   46
302 Vertical Horizon     You're A God            2000-08-26   64  55  43   41
303 Vitamin C            Graduation (Friends ... 2000-04-15   81  64  54   54
304 Vitamin C            The Itch                2000-12-02   86  48  45   52
305 Walker, Clay         Live, Laugh, Love       1999-12-04   95  95  94   94
306 Walker, Clay         The Chain Of Love       2000-04-15   73  65  57   57
307 Wallflowers, The     Sleepwalker             2000-10-28   73  73  74   80
308 Westlife             Swear It Again          2000-04-01   96  82  66   55
309 Williams, Robbie     Angels                  1999-11-20   85  77  69   69
310 Wills, Mark          Back At One             2000-01-15   89  55  51   43
311 Worley, Darryl       When You Need My Lov... 2000-06-17   98  88  93   92
312 Wright, Chely        It Was                  2000-03-04   86  78  75   72
313 Yankee Grey          Another Nine Minutes    2000-04-29   86  83  77   74
314 Yearwood, Trisha     Real Live Woman         2000-04-01   85  83  83   82
315 Ying Yang Twins      Whistle While You Tw... 2000-03-18   95  94  91   85
316 Zombie Nation        Kernkraft 400           2000-09-02   99  99  NA   NA
317 matchbox twenty      Bent                    2000-04-29   60  37  29   24
    wk5 wk6 wk7 ... wk67 wk68 wk69 wk70 wk71 wk72 wk73 wk74 wk75 wk76
1    87 94  99  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
2    NA NA  NA  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
3    66 57  54  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
4    67 65  55  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
5    17 31  36  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
6    26 19   2  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
7   100 NA  NA  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
8    38 35  35  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
9    21 18  16  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
10   68 67  61  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
11   73 69  68  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
12   23 18  11  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
13   21 19  20  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
14   13 13  11  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
15   45 36  34  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
16   92 NA  NA  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
17  100 93  93  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
18   NA NA  NA  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
19   82 81  74  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
20   30 27  21  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
21   39 33  26  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
22   26 30  35  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
23   38 34  28  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
24   12 12  10  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
25   16 14  12  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
26   31 30  39  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
27   48 42  34  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
28   65 54  61  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
29   51 37  33  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
30   62 63  54  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
... ... ... ...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
288 54  47  53  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
289 32  28  24  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
290 82  83  84  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
291 52  47  47  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
292 48  45  40  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
293 83  83  89  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
294 NA  NA  NA  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
295 63  56  50  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
296 NA  NA  NA  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
297 67  64  60  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
298 62  79  93  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
299 57  53  47  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
300 53  46  43  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
301 40  33  31  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
302 37  31  30  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
303 46  40  40  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
304 57  58  76  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
305 94  95  82  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
306 51  48  44  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
307 90  96  NA  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
308 55  46  44  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
309 62  56  56  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
310 37  37  36  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
311 85  85  84  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
312 71  69  64  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
313 83  79  88  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
314 81  91  NA  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
315 84  78  74  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
316 NA  NA  NA  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
317 22  21  18  ... NA   NA   NA   NA   NA   NA   NA   NA   NA   NA

We can start with the same basic specification as for the `relig_income` dataset. Here we want the names to become a variable called week, and the values to become a variable called rank. I also use `values_drop_na` to drop rows that correspond to missing values. Not every song stays in the charts for all 76 weeks, so the structure of the input data force the creation of unnessary explicit NAs.

In [8]:
billboard %>%
pivot_longer(
    cols = starts_with('wk'),
    names_to = 'week', 
    values_to = 'rank'
)

      artist          track                   date.entered week rank
1     2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk1  87
2     2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk2  82
3     2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk3  72
4     2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk4  77
5     2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk5  87
6     2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk6  94
7     2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk7  99
8     2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk8  NA
9     2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk9  NA
10    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk10 NA
11    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk11 NA
12    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk12 NA
13    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk13 NA
14    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk14 NA
15    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk15 NA
16    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk16 NA
17    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk17 NA
18    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk18 NA
19    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk19 NA
20    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk20 NA
21    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk21 NA
22    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk22 NA
23    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk23 NA
24    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk24 NA
25    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk25 NA
26    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk26 NA
27    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk27 NA
28    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk28 NA
29    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk29 NA
30    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk30 NA
...   ...             ...                     ...          ...  ...
24063 matchbox twenty Bent                    2000-04-29   wk47 NA
24064 matchbox twenty Bent                    2000-04-29   wk48 NA
24065 matchbox twenty Bent                    2000-04-29   wk49 NA
24066 matchbox twenty Bent                    2000-04-29   wk50 NA
24067 matchbox twenty Bent                    2000-04-29   wk51 NA
24068 matchbox twenty Bent                    2000-04-29   wk52 NA
24069 matchbox twenty Bent                    2000-04-29   wk53 NA
24070 matchbox twenty Bent                    2000-04-29   wk54 NA
24071 matchbox twenty Bent                    2000-04-29   wk55 NA
24072 matchbox twenty Bent                    2000-04-29   wk56 NA
24073 matchbox twenty Bent                    2000-04-29   wk57 NA
24074 matchbox twenty Bent                    2000-04-29   wk58 NA
24075 matchbox twenty Bent                    2000-04-29   wk59 NA
24076 matchbox twenty Bent                    2000-04-29   wk60 NA
24077 matchbox twenty Bent                    2000-04-29   wk61 NA
24078 matchbox twenty Bent                    2000-04-29   wk62 NA
24079 matchbox twenty Bent                    2000-04-29   wk63 NA
24080 matchbox twenty Bent                    2000-04-29   wk64 NA
24081 matchbox twenty Bent                    2000-04-29   wk65 NA
24082 matchbox twenty Bent                    2000-04-29   wk66 NA
24083 matchbox twenty Bent                    2000-04-29   wk67 NA
24084 matchbox twenty Bent                    2000-04-29   wk68 NA
24085 matchbox twenty Bent                    2000-04-29   wk69 NA
24086 matchbox twenty Bent                    2000-04-29   wk70 NA
24087 matchbox twenty Bent                    2000-04-29   wk71 NA
24088 matchbox twenty Bent                    2000-04-29   wk72 NA
24089 matchbox twenty Bent                    2000-04-29   wk73 NA
24090 matchbox twenty Bent                    2000-04-29   wk74 NA
24091 matchbox twenty Bent                    2000-04-29   wk75 NA
24092 matchbox twenty Bent                    2000-04-29   wk76 NA

if you wanna drop NA values, set `values_drop_na = TRUE`

In [13]:
billboard %>%
pivot_longer(
    cols = starts_with('wk'),
    names_to = 'week',
    values_to = 'count',
    values_drop_na = T
)

     artist          track                   date.entered week count
1    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk1  87
2    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk2  82
3    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk3  72
4    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk4  77
5    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk5  87
6    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk6  94
7    2 Pac           Baby Don't Cry (Keep... 2000-02-26   wk7  99
8    2Ge+her         The Hardest Part Of ... 2000-09-02   wk1  91
9    2Ge+her         The Hardest Part Of ... 2000-09-02   wk2  87
10   2Ge+her         The Hardest Part Of ... 2000-09-02   wk3  92
11   3 Doors Down    Kryptonite              2000-04-08   wk1  81
12   3 Doors Down    Kryptonite              2000-04-08   wk2  70
13   3 Doors Down    Kryptonite              2000-04-08   wk3  68
14   3 Doors Down    Kryptonite              2000-04-08   wk4  67
15   3 Doors Down    Kryptonite              2000-04-08   wk5  66
16   3 Doors Down    Kryptonite              2000-04-08   wk6  57
17   3 Doors Down    Kryptonite              2000-04-08   wk7  54
18   3 Doors Down    Kryptonite              2000-04-08   wk8  53
19   3 Doors Down    Kryptonite              2000-04-08   wk9  51
20   3 Doors Down    Kryptonite              2000-04-08   wk10 51
21   3 Doors Down    Kryptonite              2000-04-08   wk11 51
22   3 Doors Down    Kryptonite              2000-04-08   wk12 51
23   3 Doors Down    Kryptonite              2000-04-08   wk13 47
24   3 Doors Down    Kryptonite              2000-04-08   wk14 44
25   3 Doors Down    Kryptonite              2000-04-08   wk15 38
26   3 Doors Down    Kryptonite              2000-04-08   wk16 28
27   3 Doors Down    Kryptonite              2000-04-08   wk17 22
28   3 Doors Down    Kryptonite              2000-04-08   wk18 18
29   3 Doors Down    Kryptonite              2000-04-08   wk19 18
30   3 Doors Down    Kryptonite              2000-04-08   wk20 14
...  ...             ...                     ...          ...  ...
5278 matchbox twenty Bent                    2000-04-29   wk10 12
5279 matchbox twenty Bent                    2000-04-29   wk11  8
5280 matchbox twenty Bent                    2000-04-29   wk12  6
5281 matchbox twenty Bent                    2000-04-29   wk13  1
5282 matchbox twenty Bent                    2000-04-29   wk14  2
5283 matchbox twenty Bent                    2000-04-29   wk15  3
5284 matchbox twenty Bent                    2000-04-29   wk16  2
5285 matchbox twenty Bent                    2000-04-29   wk17  2
5286 matchbox twenty Bent                    2000-04-29   wk18  3
5287 matchbox twenty Bent                    2000-04-29   wk19  4
5288 matchbox twenty Bent                    2000-04-29   wk20  5
5289 matchbox twenty Bent                    2000-04-29   wk21  4
5290 matchbox twenty Bent                    2000-04-29   wk22  4
5291 matchbox twenty Bent                    2000-04-29   wk23  6
5292 matchbox twenty Bent                    2000-04-29   wk24  9
5293 matchbox twenty Bent                    2000-04-29   wk25 12
5294 matchbox twenty Bent                    2000-04-29   wk26 13
5295 matchbox twenty Bent                    2000-04-29   wk27 19
5296 matchbox twenty Bent                    2000-04-29   wk28 20
5297 matchbox twenty Bent                    2000-04-29   wk29 20
5298 matchbox twenty Bent                    2000-04-29   wk30 24
5299 matchbox twenty Bent                    2000-04-29   wk31 29
5300 matchbox twenty Bent                    2000-04-29   wk32 28
5301 matchbox twenty Bent                    2000-04-29   wk33 27
5302 matchbox twenty Bent                    2000-04-29   wk34 30
5303 matchbox twenty Bent                    2000-04-29   wk35 33
5304 matchbox twenty Bent                    2000-04-29   wk36 37
5305 matchbox twenty Bent                    2000-04-29   wk37 38
5306 matchbox twenty Bent                    2000-04-29   wk38 38
5307 matchbox twenty Bent                    2000-04-29   wk39 48

It would be nice to easily determine how long each song stayed in the charts, but to do that, we’ll need to convert the week variable to an integer. We can do that by using two additional arguments: `names_prefix` strips off the wk prefix, and `names_transform` converts week into an integer:

In [22]:
billboard %>%
pivot_longer(
    cols = starts_with('wk'),
    names_prefix = 'wk',
    names_to = 'week',
    values_to = 'rank',
    names_transform = list(week = as.integer),
    values_drop_na = T
) %>%
head()

  artist track                   date.entered week rank
1 2 Pac  Baby Don't Cry (Keep... 2000-02-26   1    87
2 2 Pac  Baby Don't Cry (Keep... 2000-02-26   2    82
3 2 Pac  Baby Don't Cry (Keep... 2000-02-26   3    72
4 2 Pac  Baby Don't Cry (Keep... 2000-02-26   4    77
5 2 Pac  Baby Don't Cry (Keep... 2000-02-26   5    87
6 2 Pac  Baby Don't Cry (Keep... 2000-02-26   6    94

Alternatively, you could do this with a single argument by using `readr::parse_number()` which automatically strips non-numeric components:

In [20]:
billboard %>%
pivot_longer(
    cols = starts_with('wk'),
    names_to = 'week',
    values_to = 'rank',
    names_transform = list(week = readr::parse_number),
    values_drop_na = T
)

     artist          track                   date.entered week rank
1    2 Pac           Baby Don't Cry (Keep... 2000-02-26    1   87
2    2 Pac           Baby Don't Cry (Keep... 2000-02-26    2   82
3    2 Pac           Baby Don't Cry (Keep... 2000-02-26    3   72
4    2 Pac           Baby Don't Cry (Keep... 2000-02-26    4   77
5    2 Pac           Baby Don't Cry (Keep... 2000-02-26    5   87
6    2 Pac           Baby Don't Cry (Keep... 2000-02-26    6   94
7    2 Pac           Baby Don't Cry (Keep... 2000-02-26    7   99
8    2Ge+her         The Hardest Part Of ... 2000-09-02    1   91
9    2Ge+her         The Hardest Part Of ... 2000-09-02    2   87
10   2Ge+her         The Hardest Part Of ... 2000-09-02    3   92
11   3 Doors Down    Kryptonite              2000-04-08    1   81
12   3 Doors Down    Kryptonite              2000-04-08    2   70
13   3 Doors Down    Kryptonite              2000-04-08    3   68
14   3 Doors Down    Kryptonite              2000-04-08    4   67
15   3 Doors Down    Kryptonite              2000-04-08    5   66
16   3 Doors Down    Kryptonite              2000-04-08    6   57
17   3 Doors Down    Kryptonite              2000-04-08    7   54
18   3 Doors Down    Kryptonite              2000-04-08    8   53
19   3 Doors Down    Kryptonite              2000-04-08    9   51
20   3 Doors Down    Kryptonite              2000-04-08   10   51
21   3 Doors Down    Kryptonite              2000-04-08   11   51
22   3 Doors Down    Kryptonite              2000-04-08   12   51
23   3 Doors Down    Kryptonite              2000-04-08   13   47
24   3 Doors Down    Kryptonite              2000-04-08   14   44
25   3 Doors Down    Kryptonite              2000-04-08   15   38
26   3 Doors Down    Kryptonite              2000-04-08   16   28
27   3 Doors Down    Kryptonite              2000-04-08   17   22
28   3 Doors Down    Kryptonite              2000-04-08   18   18
29   3 Doors Down    Kryptonite              2000-04-08   19   18
30   3 Doors Down    Kryptonite              2000-04-08   20   14
...  ...             ...                     ...          ...  ...
5278 matchbox twenty Bent                    2000-04-29   10   12
5279 matchbox twenty Bent                    2000-04-29   11    8
5280 matchbox twenty Bent                    2000-04-29   12    6
5281 matchbox twenty Bent                    2000-04-29   13    1
5282 matchbox twenty Bent                    2000-04-29   14    2
5283 matchbox twenty Bent                    2000-04-29   15    3
5284 matchbox twenty Bent                    2000-04-29   16    2
5285 matchbox twenty Bent                    2000-04-29   17    2
5286 matchbox twenty Bent                    2000-04-29   18    3
5287 matchbox twenty Bent                    2000-04-29   19    4
5288 matchbox twenty Bent                    2000-04-29   20    5
5289 matchbox twenty Bent                    2000-04-29   21    4
5290 matchbox twenty Bent                    2000-04-29   22    4
5291 matchbox twenty Bent                    2000-04-29   23    6
5292 matchbox twenty Bent                    2000-04-29   24    9
5293 matchbox twenty Bent                    2000-04-29   25   12
5294 matchbox twenty Bent                    2000-04-29   26   13
5295 matchbox twenty Bent                    2000-04-29   27   19
5296 matchbox twenty Bent                    2000-04-29   28   20
5297 matchbox twenty Bent                    2000-04-29   29   20
5298 matchbox twenty Bent                    2000-04-29   30   24
5299 matchbox twenty Bent                    2000-04-29   31   29
5300 matchbox twenty Bent                    2000-04-29   32   28
5301 matchbox twenty Bent                    2000-04-29   33   27
5302 matchbox twenty Bent                    2000-04-29   34   30
5303 matchbox twenty Bent                    2000-04-29   35   33
5304 matchbox twenty Bent                    2000-04-29   36   37
5305 matchbox twenty Bent                    2000-04-29   37   38
5306 matchbox twenty Bent                    2000-04-29   38   38
5307 matchbox twenty Bent                    2000-04-29   39   48

<hr>
<b style = 'color:red'>SELF UNDERSTANDING</b>

To understand how it works internally, it is best to look at only 1 observation:

In [46]:
bb <- billboard %>% slice(1)
bb

  artist track                   date.entered wk1 wk2 wk3 wk4 wk5 wk6 wk7 ...
1 2 Pac  Baby Don't Cry (Keep... 2000-02-26   87  82  72  77  87  94  99  ...
  wk67 wk68 wk69 wk70 wk71 wk72 wk73 wk74 wk75 wk76
1 NA   NA   NA   NA   NA   NA   NA   NA   NA   NA

In [48]:
#let's try simple pivot
bb %>% pivot_longer(
    cols = starts_with('wk'),
    names_to = 'week',
    values_to = 'rank'
)

    artist track                   date.entered week rank
1   2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk1  87
2   2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk2  82
3   2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk3  72
4   2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk4  77
5   2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk5  87
6   2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk6  94
7   2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk7  99
8   2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk8  NA
9   2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk9  NA
10  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk10 NA
11  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk11 NA
12  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk12 NA
13  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk13 NA
14  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk14 NA
15  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk15 NA
16  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk16 NA
17  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk17 NA
18  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk18 NA
19  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk19 NA
20  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk20 NA
21  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk21 NA
22  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk22 NA
23  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk23 NA
24  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk24 NA
25  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk25 NA
26  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk26 NA
27  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk27 NA
28  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk28 NA
29  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk29 NA
30  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk30 NA
... ...    ...                     ...          ...  ...
47  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk47 NA
48  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk48 NA
49  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk49 NA
50  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk50 NA
51  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk51 NA
52  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk52 NA
53  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk53 NA
54  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk54 NA
55  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk55 NA
56  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk56 NA
57  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk57 NA
58  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk58 NA
59  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk59 NA
60  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk60 NA
61  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk61 NA
62  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk62 NA
63  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk63 NA
64  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk64 NA
65  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk65 NA
66  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk66 NA
67  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk67 NA
68  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk68 NA
69  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk69 NA
70  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk70 NA
71  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk71 NA
72  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk72 NA
73  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk73 NA
74  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk74 NA
75  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk75 NA
76  2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk76 NA

In [49]:
bb %>% pivot_longer(
    cols = starts_with('wk'),
    names_to = 'week',
    values_to = 'rank',
    names_prefix = 'wk',                      #remove prefix 'wk' in column `week` of above data frame
    names_transfrom = list(week = as.integer) #convert to integer (e.g: '75' to 75)
)

    artist track                   date.entered week rank
1   2 Pac  Baby Don't Cry (Keep... 2000-02-26   1    87
2   2 Pac  Baby Don't Cry (Keep... 2000-02-26   2    82
3   2 Pac  Baby Don't Cry (Keep... 2000-02-26   3    72
4   2 Pac  Baby Don't Cry (Keep... 2000-02-26   4    77
5   2 Pac  Baby Don't Cry (Keep... 2000-02-26   5    87
6   2 Pac  Baby Don't Cry (Keep... 2000-02-26   6    94
7   2 Pac  Baby Don't Cry (Keep... 2000-02-26   7    99
8   2 Pac  Baby Don't Cry (Keep... 2000-02-26   8    NA
9   2 Pac  Baby Don't Cry (Keep... 2000-02-26   9    NA
10  2 Pac  Baby Don't Cry (Keep... 2000-02-26   10   NA
11  2 Pac  Baby Don't Cry (Keep... 2000-02-26   11   NA
12  2 Pac  Baby Don't Cry (Keep... 2000-02-26   12   NA
13  2 Pac  Baby Don't Cry (Keep... 2000-02-26   13   NA
14  2 Pac  Baby Don't Cry (Keep... 2000-02-26   14   NA
15  2 Pac  Baby Don't Cry (Keep... 2000-02-26   15   NA
16  2 Pac  Baby Don't Cry (Keep... 2000-02-26   16   NA
17  2 Pac  Baby Don't Cry (Keep... 2000-02-26   17   NA
18  2 Pac  Baby Don't Cry (Keep... 2000-02-26   18   NA
19  2 Pac  Baby Don't Cry (Keep... 2000-02-26   19   NA
20  2 Pac  Baby Don't Cry (Keep... 2000-02-26   20   NA
21  2 Pac  Baby Don't Cry (Keep... 2000-02-26   21   NA
22  2 Pac  Baby Don't Cry (Keep... 2000-02-26   22   NA
23  2 Pac  Baby Don't Cry (Keep... 2000-02-26   23   NA
24  2 Pac  Baby Don't Cry (Keep... 2000-02-26   24   NA
25  2 Pac  Baby Don't Cry (Keep... 2000-02-26   25   NA
26  2 Pac  Baby Don't Cry (Keep... 2000-02-26   26   NA
27  2 Pac  Baby Don't Cry (Keep... 2000-02-26   27   NA
28  2 Pac  Baby Don't Cry (Keep... 2000-02-26   28   NA
29  2 Pac  Baby Don't Cry (Keep... 2000-02-26   29   NA
30  2 Pac  Baby Don't Cry (Keep... 2000-02-26   30   NA
... ...    ...                     ...          ...  ...
47  2 Pac  Baby Don't Cry (Keep... 2000-02-26   47   NA
48  2 Pac  Baby Don't Cry (Keep... 2000-02-26   48   NA
49  2 Pac  Baby Don't Cry (Keep... 2000-02-26   49   NA
50  2 Pac  Baby Don't Cry (Keep... 2000-02-26   50   NA
51  2 Pac  Baby Don't Cry (Keep... 2000-02-26   51   NA
52  2 Pac  Baby Don't Cry (Keep... 2000-02-26   52   NA
53  2 Pac  Baby Don't Cry (Keep... 2000-02-26   53   NA
54  2 Pac  Baby Don't Cry (Keep... 2000-02-26   54   NA
55  2 Pac  Baby Don't Cry (Keep... 2000-02-26   55   NA
56  2 Pac  Baby Don't Cry (Keep... 2000-02-26   56   NA
57  2 Pac  Baby Don't Cry (Keep... 2000-02-26   57   NA
58  2 Pac  Baby Don't Cry (Keep... 2000-02-26   58   NA
59  2 Pac  Baby Don't Cry (Keep... 2000-02-26   59   NA
60  2 Pac  Baby Don't Cry (Keep... 2000-02-26   60   NA
61  2 Pac  Baby Don't Cry (Keep... 2000-02-26   61   NA
62  2 Pac  Baby Don't Cry (Keep... 2000-02-26   62   NA
63  2 Pac  Baby Don't Cry (Keep... 2000-02-26   63   NA
64  2 Pac  Baby Don't Cry (Keep... 2000-02-26   64   NA
65  2 Pac  Baby Don't Cry (Keep... 2000-02-26   65   NA
66  2 Pac  Baby Don't Cry (Keep... 2000-02-26   66   NA
67  2 Pac  Baby Don't Cry (Keep... 2000-02-26   67   NA
68  2 Pac  Baby Don't Cry (Keep... 2000-02-26   68   NA
69  2 Pac  Baby Don't Cry (Keep... 2000-02-26   69   NA
70  2 Pac  Baby Don't Cry (Keep... 2000-02-26   70   NA
71  2 Pac  Baby Don't Cry (Keep... 2000-02-26   71   NA
72  2 Pac  Baby Don't Cry (Keep... 2000-02-26   72   NA
73  2 Pac  Baby Don't Cry (Keep... 2000-02-26   73   NA
74  2 Pac  Baby Don't Cry (Keep... 2000-02-26   74   NA
75  2 Pac  Baby Don't Cry (Keep... 2000-02-26   75   NA
76  2 Pac  Baby Don't Cry (Keep... 2000-02-26   76   NA

### Many variables in column name

A more challenging situation occurs when you have multiple variables crammed into the column names. For example, take the `who` dataset:

In [23]:
who %>% head()

  country     iso2 iso3 year new_sp_m014 new_sp_m1524 new_sp_m2534 new_sp_m3544
1 Afghanistan AF   AFG  1980 NA          NA           NA           NA
2 Afghanistan AF   AFG  1981 NA          NA           NA           NA
3 Afghanistan AF   AFG  1982 NA          NA           NA           NA
4 Afghanistan AF   AFG  1983 NA          NA           NA           NA
5 Afghanistan AF   AFG  1984 NA          NA           NA           NA
6 Afghanistan AF   AFG  1985 NA          NA           NA           NA
  new_sp_m4554 new_sp_m5564 ... newrel_m4554 newrel_m5564 newrel_m65
1 NA           NA           ... NA           NA           NA
2 NA           NA           ... NA           NA           NA
3 NA           NA           ... NA           NA           NA
4 NA           NA           ... NA           NA           NA
5 NA           NA           ... NA           NA           NA
6 NA           NA           ... NA           NA           NA
  newrel_f014 newrel_f1524 newrel_f2534 newrel_f3544 newrel_f4554 newrel_f5564
1 NA          NA           NA           NA           NA           NA
2 NA          NA           NA           NA           NA           NA
3 NA          NA           NA           NA           NA           NA
4 NA          NA           NA           NA           NA           NA
5 NA          NA           NA           NA           NA           NA
6 NA          NA           NA           NA           NA           NA
  newrel_f65
1 NA
2 NA
3 NA
4 NA
5 NA
6 NA

country, iso2, iso3, and year are already variables, so they can be left as is. But the columns from new_sp_m014 to newrel_f65 encode four variables in their names:

*  The `new_/new` prefix indicates these are counts of new cases. This dataset only contains new cases, so we’ll ignore it here because it’s constant.

*  `sp/rel/ep` describe how the case was diagnosed.

*  `m/f` gives the gender.

*  `014/1524/2535/3544/4554/65` supplies the age range.

In [30]:
#let's try simple pivot
who %>% pivot_longer(
    cols = new_sp_m014:newrel_f65,
    names_to = 'infomation',
    values_to = 'count'
) %>% head()

  country     iso2 iso3 year infomation   count
1 Afghanistan AF   AFG  1980 new_sp_m014  NA
2 Afghanistan AF   AFG  1980 new_sp_m1524 NA
3 Afghanistan AF   AFG  1980 new_sp_m2534 NA
4 Afghanistan AF   AFG  1980 new_sp_m3544 NA
5 Afghanistan AF   AFG  1980 new_sp_m4554 NA
6 Afghanistan AF   AFG  1980 new_sp_m5564 NA

We can break these variables up by specifying multiple column names in names_to, and then either providing `names_sep` or `names_pattern`. Here `names_pattern` is the most natural fit. It has a similar interface to extract: you give it a regular expression containing groups (defined by `()`) and it puts each group in a column.

In [26]:
#Love at the result above
#In this case, we transformed column `information` from the data frame above
#to 3 columns: diagnosis, age and count
who %>% pivot_longer(
  cols = new_sp_m014:newrel_f65,
  names_to = c("diagnosis", "gender", "age"),
  names_pattern = "new_?(.*)_(.)(.*)",
  values_to = "count"
)

       country     iso2 iso3 year diagnosis gender age  count
1      Afghanistan AF   AFG  1980 sp        m      014  NA
2      Afghanistan AF   AFG  1980 sp        m      1524 NA
3      Afghanistan AF   AFG  1980 sp        m      2534 NA
4      Afghanistan AF   AFG  1980 sp        m      3544 NA
5      Afghanistan AF   AFG  1980 sp        m      4554 NA
6      Afghanistan AF   AFG  1980 sp        m      5564 NA
7      Afghanistan AF   AFG  1980 sp        m      65   NA
8      Afghanistan AF   AFG  1980 sp        f      014  NA
9      Afghanistan AF   AFG  1980 sp        f      1524 NA
10     Afghanistan AF   AFG  1980 sp        f      2534 NA
11     Afghanistan AF   AFG  1980 sp        f      3544 NA
12     Afghanistan AF   AFG  1980 sp        f      4554 NA
13     Afghanistan AF   AFG  1980 sp        f      5564 NA
14     Afghanistan AF   AFG  1980 sp        f      65   NA
15     Afghanistan AF   AFG  1980 sn        m      014  NA
16     Afghanistan AF   AFG  1980 sn        m      1524 NA
17     Afghanistan AF   AFG  1980 sn        m      2534 NA
18     Afghanistan AF   AFG  1980 sn        m      3544 NA
19     Afghanistan AF   AFG  1980 sn        m      4554 NA
20     Afghanistan AF   AFG  1980 sn        m      5564 NA
21     Afghanistan AF   AFG  1980 sn        m      65   NA
22     Afghanistan AF   AFG  1980 sn        f      014  NA
23     Afghanistan AF   AFG  1980 sn        f      1524 NA
24     Afghanistan AF   AFG  1980 sn        f      2534 NA
25     Afghanistan AF   AFG  1980 sn        f      3544 NA
26     Afghanistan AF   AFG  1980 sn        f      4554 NA
27     Afghanistan AF   AFG  1980 sn        f      5564 NA
28     Afghanistan AF   AFG  1980 sn        f      65   NA
29     Afghanistan AF   AFG  1980 ep        m      014  NA
30     Afghanistan AF   AFG  1980 ep        m      1524 NA
...    ...         ...  ...  ...  ...       ...    ...  ...
405411 Zimbabwe    ZW   ZWE  2013 sn        f      5564   NA
405412 Zimbabwe    ZW   ZWE  2013 sn        f      65     NA
405413 Zimbabwe    ZW   ZWE  2013 ep        m      014    NA
405414 Zimbabwe    ZW   ZWE  2013 ep        m      1524   NA
405415 Zimbabwe    ZW   ZWE  2013 ep        m      2534   NA
405416 Zimbabwe    ZW   ZWE  2013 ep        m      3544   NA
405417 Zimbabwe    ZW   ZWE  2013 ep        m      4554   NA
405418 Zimbabwe    ZW   ZWE  2013 ep        m      5564   NA
405419 Zimbabwe    ZW   ZWE  2013 ep        m      65     NA
405420 Zimbabwe    ZW   ZWE  2013 ep        f      014    NA
405421 Zimbabwe    ZW   ZWE  2013 ep        f      1524   NA
405422 Zimbabwe    ZW   ZWE  2013 ep        f      2534   NA
405423 Zimbabwe    ZW   ZWE  2013 ep        f      3544   NA
405424 Zimbabwe    ZW   ZWE  2013 ep        f      4554   NA
405425 Zimbabwe    ZW   ZWE  2013 ep        f      5564   NA
405426 Zimbabwe    ZW   ZWE  2013 ep        f      65     NA
405427 Zimbabwe    ZW   ZWE  2013 rel       m      014  1315
405428 Zimbabwe    ZW   ZWE  2013 rel       m      1524 1642
405429 Zimbabwe    ZW   ZWE  2013 rel       m      2534 5331
405430 Zimbabwe    ZW   ZWE  2013 rel       m      3544 5363
405431 Zimbabwe    ZW   ZWE  2013 rel       m      4554 2349
405432 Zimbabwe    ZW   ZWE  2013 rel       m      5564 1206
405433 Zimbabwe    ZW   ZWE  2013 rel       m      65   1208
405434 Zimbabwe    ZW   ZWE  2013 rel       f      014  1252
405435 Zimbabwe    ZW   ZWE  2013 rel       f      1524 2069
405436 Zimbabwe    ZW   ZWE  2013 rel       f      2534 4649
405437 Zimbabwe    ZW   ZWE  2013 rel       f      3544 3526
405438 Zimbabwe    ZW   ZWE  2013 rel       f      4554 1453
405439 Zimbabwe    ZW   ZWE  2013 rel       f      5564  811
405440 Zimbabwe    ZW   ZWE  2013 rel       f      65    725

We could go one step further use `readr` functions to convert the `gender` and `age` to factors. I think this is good practice when you have categorical variables with a known set of values.

In [35]:
who %>%
pivot_longer(
    cols = new_sp_m014:newrel_f65,
    names_pattern = 'new_?(.*)_(.)(.*)',
    names_to = c('diagnosis', 'sex', 'age'),
    values_to = 'count',
    names_transform = list(sex = as.factor, age = as.factor)
) %>% str

tibble [405,440 x 8] (S3: tbl_df/tbl/data.frame)
 $ country  : chr [1:405440] "Afghanistan" "Afghanistan" "Afghanistan" "Afghanistan" ...
 $ iso2     : chr [1:405440] "AF" "AF" "AF" "AF" ...
 $ iso3     : chr [1:405440] "AFG" "AFG" "AFG" "AFG" ...
 $ year     : int [1:405440] 1980 1980 1980 1980 1980 1980 1980 1980 1980 1980 ...
 $ diagnosis: chr [1:405440] "sp" "sp" "sp" "sp" ...
 $ sex      : Factor w/ 2 levels "f","m": 2 2 2 2 2 2 2 1 1 1 ...
 $ age      : Factor w/ 7 levels "014","1524","2534",..: 1 2 3 4 5 6 7 1 2 3 ...
 $ count    : int [1:405440] NA NA NA NA NA NA NA NA NA NA ...

<hr>
<b style = 'color:red'>SELF UNDERSTANDING</b>

To understand how it works internally, it is best to look at only 1 observation:

In [50]:
who1 <- who %>% slice(1)
who1

  country     iso2 iso3 year new_sp_m014 new_sp_m1524 new_sp_m2534 new_sp_m3544
1 Afghanistan AF   AFG  1980 NA          NA           NA           NA
  new_sp_m4554 new_sp_m5564 ... newrel_m4554 newrel_m5564 newrel_m65
1 NA           NA           ... NA           NA           NA
  newrel_f014 newrel_f1524 newrel_f2534 newrel_f3544 newrel_f4554 newrel_f5564
1 NA          NA           NA           NA           NA           NA
  newrel_f65
1 NA

In [51]:
#simple pivot_longer
who1 %>% pivot_longer(
    cols = new_sp_m014:newrel_f65,
    names_to = 'information',
    values_to = 'count'
)

   country     iso2 iso3 year information  count
1  Afghanistan AF   AFG  1980 new_sp_m014  NA
2  Afghanistan AF   AFG  1980 new_sp_m1524 NA
3  Afghanistan AF   AFG  1980 new_sp_m2534 NA
4  Afghanistan AF   AFG  1980 new_sp_m3544 NA
5  Afghanistan AF   AFG  1980 new_sp_m4554 NA
6  Afghanistan AF   AFG  1980 new_sp_m5564 NA
7  Afghanistan AF   AFG  1980 new_sp_m65   NA
8  Afghanistan AF   AFG  1980 new_sp_f014  NA
9  Afghanistan AF   AFG  1980 new_sp_f1524 NA
10 Afghanistan AF   AFG  1980 new_sp_f2534 NA
11 Afghanistan AF   AFG  1980 new_sp_f3544 NA
12 Afghanistan AF   AFG  1980 new_sp_f4554 NA
13 Afghanistan AF   AFG  1980 new_sp_f5564 NA
14 Afghanistan AF   AFG  1980 new_sp_f65   NA
15 Afghanistan AF   AFG  1980 new_sn_m014  NA
16 Afghanistan AF   AFG  1980 new_sn_m1524 NA
17 Afghanistan AF   AFG  1980 new_sn_m2534 NA
18 Afghanistan AF   AFG  1980 new_sn_m3544 NA
19 Afghanistan AF   AFG  1980 new_sn_m4554 NA
20 Afghanistan AF   AFG  1980 new_sn_m5564 NA
21 Afghanistan AF   AFG  1980 new_sn_m65   NA
22 Afghanistan AF   AFG  1980 new_sn_f014  NA
23 Afghanistan AF   AFG  1980 new_sn_f1524 NA
24 Afghanistan AF   AFG  1980 new_sn_f2534 NA
25 Afghanistan AF   AFG  1980 new_sn_f3544 NA
26 Afghanistan AF   AFG  1980 new_sn_f4554 NA
27 Afghanistan AF   AFG  1980 new_sn_f5564 NA
28 Afghanistan AF   AFG  1980 new_sn_f65   NA
29 Afghanistan AF   AFG  1980 new_ep_m014  NA
30 Afghanistan AF   AFG  1980 new_ep_m1524 NA
31 Afghanistan AF   AFG  1980 new_ep_m2534 NA
32 Afghanistan AF   AFG  1980 new_ep_m3544 NA
33 Afghanistan AF   AFG  1980 new_ep_m4554 NA
34 Afghanistan AF   AFG  1980 new_ep_m5564 NA
35 Afghanistan AF   AFG  1980 new_ep_m65   NA
36 Afghanistan AF   AFG  1980 new_ep_f014  NA
37 Afghanistan AF   AFG  1980 new_ep_f1524 NA
38 Afghanistan AF   AFG  1980 new_ep_f2534 NA
39 Afghanistan AF   AFG  1980 new_ep_f3544 NA
40 Afghanistan AF   AFG  1980 new_ep_f4554 NA
41 Afghanistan AF   AFG  1980 new_ep_f5564 NA
42 Afghanistan AF   AFG  1980 new_ep_f65   NA
43 Afghanistan AF   AFG  1980 newrel_m014  NA
44 Afghanistan AF   AFG  1980 newrel_m1524 NA
45 Afghanistan AF   AFG  1980 newrel_m2534 NA
46 Afghanistan AF   AFG  1980 newrel_m3544 NA
47 Afghanistan AF   AFG  1980 newrel_m4554 NA
48 Afghanistan AF   AFG  1980 newrel_m5564 NA
49 Afghanistan AF   AFG  1980 newrel_m65   NA
50 Afghanistan AF   AFG  1980 newrel_f014  NA
51 Afghanistan AF   AFG  1980 newrel_f1524 NA
52 Afghanistan AF   AFG  1980 newrel_f2534 NA
53 Afghanistan AF   AFG  1980 newrel_f3544 NA
54 Afghanistan AF   AFG  1980 newrel_f4554 NA
55 Afghanistan AF   AFG  1980 newrel_f5564 NA
56 Afghanistan AF   AFG  1980 newrel_f65   NA

In [52]:
#breaks `information` to 3 columns: `diagnosis`, `sex` and `age`
who1 %>% pivot_longer(
    cols = new_sp_m014:newrel_f65,
    names_pattern = 'new_?(.*)?_(.)(.*)',
    names_to = c('diagnosis', 'sex', 'age'),
    values_to = 'count'
)

   country     iso2 iso3 year diagnosis sex age  count
1  Afghanistan AF   AFG  1980 sp        m   014  NA
2  Afghanistan AF   AFG  1980 sp        m   1524 NA
3  Afghanistan AF   AFG  1980 sp        m   2534 NA
4  Afghanistan AF   AFG  1980 sp        m   3544 NA
5  Afghanistan AF   AFG  1980 sp        m   4554 NA
6  Afghanistan AF   AFG  1980 sp        m   5564 NA
7  Afghanistan AF   AFG  1980 sp        m   65   NA
8  Afghanistan AF   AFG  1980 sp        f   014  NA
9  Afghanistan AF   AFG  1980 sp        f   1524 NA
10 Afghanistan AF   AFG  1980 sp        f   2534 NA
11 Afghanistan AF   AFG  1980 sp        f   3544 NA
12 Afghanistan AF   AFG  1980 sp        f   4554 NA
13 Afghanistan AF   AFG  1980 sp        f   5564 NA
14 Afghanistan AF   AFG  1980 sp        f   65   NA
15 Afghanistan AF   AFG  1980 sn        m   014  NA
16 Afghanistan AF   AFG  1980 sn        m   1524 NA
17 Afghanistan AF   AFG  1980 sn        m   2534 NA
18 Afghanistan AF   AFG  1980 sn        m   3544 NA
19 Afghanistan AF   AFG  1980 sn        m   4554 NA
20 Afghanistan AF   AFG  1980 sn        m   5564 NA
21 Afghanistan AF   AFG  1980 sn        m   65   NA
22 Afghanistan AF   AFG  1980 sn        f   014  NA
23 Afghanistan AF   AFG  1980 sn        f   1524 NA
24 Afghanistan AF   AFG  1980 sn        f   2534 NA
25 Afghanistan AF   AFG  1980 sn        f   3544 NA
26 Afghanistan AF   AFG  1980 sn        f   4554 NA
27 Afghanistan AF   AFG  1980 sn        f   5564 NA
28 Afghanistan AF   AFG  1980 sn        f   65   NA
29 Afghanistan AF   AFG  1980 ep        m   014  NA
30 Afghanistan AF   AFG  1980 ep        m   1524 NA
31 Afghanistan AF   AFG  1980 ep        m   2534 NA
32 Afghanistan AF   AFG  1980 ep        m   3544 NA
33 Afghanistan AF   AFG  1980 ep        m   4554 NA
34 Afghanistan AF   AFG  1980 ep        m   5564 NA
35 Afghanistan AF   AFG  1980 ep        m   65   NA
36 Afghanistan AF   AFG  1980 ep        f   014  NA
37 Afghanistan AF   AFG  1980 ep        f   1524 NA
38 Afghanistan AF   AFG  1980 ep        f   2534 NA
39 Afghanistan AF   AFG  1980 ep        f   3544 NA
40 Afghanistan AF   AFG  1980 ep        f   4554 NA
41 Afghanistan AF   AFG  1980 ep        f   5564 NA
42 Afghanistan AF   AFG  1980 ep        f   65   NA
43 Afghanistan AF   AFG  1980 rel       m   014  NA
44 Afghanistan AF   AFG  1980 rel       m   1524 NA
45 Afghanistan AF   AFG  1980 rel       m   2534 NA
46 Afghanistan AF   AFG  1980 rel       m   3544 NA
47 Afghanistan AF   AFG  1980 rel       m   4554 NA
48 Afghanistan AF   AFG  1980 rel       m   5564 NA
49 Afghanistan AF   AFG  1980 rel       m   65   NA
50 Afghanistan AF   AFG  1980 rel       f   014  NA
51 Afghanistan AF   AFG  1980 rel       f   1524 NA
52 Afghanistan AF   AFG  1980 rel       f   2534 NA
53 Afghanistan AF   AFG  1980 rel       f   3544 NA
54 Afghanistan AF   AFG  1980 rel       f   4554 NA
55 Afghanistan AF   AFG  1980 rel       f   5564 NA
56 Afghanistan AF   AFG  1980 rel       f   65   NA

### Multiple observations per row

So far, we have been working with data frames that have one observation per row, but many important pivotting problems involve multiple observations per row. You can usually recognise this case because name of the column that you want to appear in the output is part of the column name in the input. In this section, you’ll learn how to pivot this sort of data.

In [36]:
family <- tribble(
  ~family,  ~dob_child1,  ~dob_child2, ~gender_child1, ~gender_child2,
       1L, "1998-11-26", "2000-01-29",             1L,             2L,
       2L, "1996-06-22",           NA,             2L,             NA,
       3L, "2002-07-11", "2004-04-05",             2L,             2L,
       4L, "2004-10-10", "2009-08-27",             1L,             1L,
       5L, "2000-12-05", "2005-02-28",             2L,             1L,
)
family <- family %>% mutate_at(vars(starts_with("dob")), parse_date)
family

  family dob_child1 dob_child2 gender_child1 gender_child2
1 1      1998-11-26 2000-01-29 1              2
2 2      1996-06-22 <NA>       2             NA
3 3      2002-07-11 2004-04-05 2              2
4 4      2004-10-10 2009-08-27 1              1
5 5      2000-12-05 2005-02-28 2              1

Note that we have two pieces of information (or values) for each child: their `gender` and their `dob` (date of birth). These need to go into separate columns in the result. Again we supply multiple variables to `names_to`, using `names_sep` to split up each variable name. Note the special name `.value`: this tells `pivot_longer()` that that part of the column name specifies the “value” being measured (which will become a variable in the output).

In [39]:
family %>%
pivot_longer(
    cols = !family,
    names_to = c(".value", "child"),
    names_sep = "_",
    values_drop_na = TRUE
)

  family child  dob        gender
1 1      child1 1998-11-26 1
2 1      child2 2000-01-29 2
3 2      child1 1996-06-22 2
4 3      child1 2002-07-11 2
5 3      child2 2004-04-05 2
6 4      child1 2004-10-10 1
7 4      child2 2009-08-27 1
8 5      child1 2000-12-05 2
9 5      child2 2005-02-28 1

This problem also exists in the `anscombe` dataset built in to base R:

In [41]:
anscombe

   x1 x2 x3 x4 y1    y2   y3    y4
1  10 10 10  8  8.04 9.14  7.46  6.58
2   8  8  8  8  6.95 8.14  6.77  5.76
3  13 13 13  8  7.58 8.74 12.74  7.71
4   9  9  9  8  8.81 8.77  7.11  8.84
5  11 11 11  8  8.33 9.26  7.81  8.47
6  14 14 14  8  9.96 8.10  8.84  7.04
7   6  6  6  8  7.24 6.13  6.08  5.25
8   4  4  4 19  4.26 3.10  5.39 12.50
9  12 12 12  8 10.84 9.13  8.15  5.56
10  7  7  7  8  4.82 7.26  6.42  7.91
11  5  5  5  8  5.68 4.74  5.73  6.89

In [59]:
#Look at only the first observation
anscombe %>% slice(1) %>%
  pivot_longer(everything(),
    names_to = c(".value", "set"),
    names_pattern = "(.)(.)"
  ) %>%
  arrange(set)

  set x  y
1 1   10 8.04
2 2   10 9.14
3 3   10 7.46
4 4    8 6.58

<hr>
<b style = 'color:red'>SELF UNDERSTANDING</b>

To understand how it works internally, it is best to look at only 1 observation:

In [53]:
f <- family %>% slice(1)
f

  family dob_child1 dob_child2 gender_child1 gender_child2
1 1      1998-11-26 2000-01-29 1             2

if we use simple pivot_longer:
```r
#This will raise an error because the last column contains different datatypes: date and integer
#But let's assume it is true to under stand 

f %>% pivot_longer(
    cols = !family,
    names_to = 'names',
    values_to =  'values'
)
```
The result will be below

names            values
----------------|----------
dob_child1      |1998-11-26
dob_child2      |2000-01-29
gender_child1   |         1
gender_child2   |         2

add `name_sep = '_'`  
add `names_to = c('dob_gender', 'child')`
```R
f %>% pivot_longer(
    cols = !family,
    names_sep = '_',
    names_to = c('dob_gender', 'child'),
    values_to = 'values'
    
)
```
The result will be like below:

dob_gender   child     values
------------|---------|----------
dob         |child1   |1998-11-26
dob         |child2   |2000-01-29
gender      |child1   |         1
gender      |child2   |         2

In [61]:
#Origin
f


#Result
f %>% pivot_longer(
    cols = !family,
    names_sep = '_',
    names_to = c('.value', 'child')
)

  family dob_child1 dob_child2 gender_child1 gender_child2
1 1      1998-11-26 2000-01-29 1             2

  family child  dob        gender
1 1      child1 1998-11-26 1
2 1      child2 2000-01-29 2

### Duplicated column names

Occassionally you will come across datasets that have duplicated column names. Generally, such datasets are hard to work with in R, because when you refer to a column by name it only finds the first match. To create a tibble with duplicated names, you have to explicitly opt out of the name repair that usually prevents you from creating such a dataset:

In [62]:
df <- tibble(id = 1:3, y = 4:6, y = 5:7, y = 7:9, .name_repair = "minimal")
df

  id y y y
1 1  4 5 7
2 2  5 6 8
3 3  6 7 9

When `pivot_longer()` encounters such data, it automatically adds another column to the output:

In [63]:
df %>% pivot_longer(
    cols = !id,
    names_to = 'names',
    values_to = 'values'
)

  id names values
1 1  y     4
2 1  y     5
3 1  y     7
4 2  y     5
5 2  y     6
6 2  y     8
7 3  y     6
8 3  y     7
9 3  y     9

A similar process is applied when multiple input columns are mapped to the same output column, as in the following example where we ignore the numeric suffix on each column name:

In [64]:
df <- tibble(id = 1:3, x1 = 4:6, x2 = 5:7, y1 = 7:9, y2 = 10:12)
df

  id x1 x2 y1 y2
1 1  4  5  7  10
2 2  5  6  8  11
3 3  6  7  9  12

In [65]:
df %>% pivot_longer(!id, names_to = ".value", names_pattern = "(.).")

  id x y
1 1  4  7
2 1  5 10
3 2  5  8
4 2  6 11
5 3  6  9
6 3  7 12

# Wider

```r
pivot_wider(
  data,
  id_cols = NULL,
  names_from = name,
  names_prefix = "",
  names_sep = "_",
  names_glue = NULL,
  names_sort = FALSE,
  names_repair = "check_unique",
  values_from = value,
  values_fill = NULL,
  values_fn = NULL,
  ...
)
```

`pivot_wider()` is the opposite of `pivot_longer()`: it makes a dataset wider by increasing the number of columns and decreasing the number of rows. It’s relatively rare to need `pivot_wider()` to make tidy data, but it’s often useful for creating summary tables for presentation, or data in a format needed by other tools.

### Capture-recapture data

The `fish_encounters` dataset, contributed by Myfanwy Johnston, describes when fish swimming down a river are detected by automatic monitoring stations:

In [70]:
fish_encounters

    fish station seen
1   4842 Release 1
2   4842 I80_1   1
3   4842 Lisbon  1
4   4842 Rstr    1
5   4842 Base_TD 1
6   4842 BCE     1
7   4842 BCW     1
8   4842 BCE2    1
9   4842 BCW2    1
10  4842 MAE     1
11  4842 MAW     1
12  4843 Release 1
13  4843 I80_1   1
14  4843 Lisbon  1
15  4843 Rstr    1
16  4843 Base_TD 1
17  4843 BCE     1
18  4843 BCW     1
19  4843 BCE2    1
20  4843 BCW2    1
21  4843 MAE     1
22  4843 MAW     1
23  4844 Release 1
24  4844 I80_1   1
25  4844 Lisbon  1
26  4844 Rstr    1
27  4844 Base_TD 1
28  4844 BCE     1
29  4844 BCW     1
30  4844 BCE2    1
... ...  ...     ...
85  4859 Lisbon  1
86  4859 Rstr    1
87  4859 Base_TD 1
88  4861 Release 1
89  4861 I80_1   1
90  4861 Lisbon  1
91  4861 Rstr    1
92  4861 Base_TD 1
93  4861 BCE     1
94  4861 BCW     1
95  4861 BCE2    1
96  4861 BCW2    1
97  4861 MAE     1
98  4861 MAW     1
99  4862 Release 1
100 4862 I80_1   1
101 4862 Lisbon  1
102 4862 Rstr    1
103 4862 Base_TD 1
104 4862 BCE     1
105 4862 BCW     1
106 4862 BCE2    1
107 4862 BCW2    1
108 4863 Release 1
109 4863 I80_1   1
110 4864 Release 1
111 4864 I80_1   1
112 4865 Release 1
113 4865 I80_1   1
114 4865 Lisbon  1

Many tools used to analyse this data need it in a form where each station is a column:

In [71]:
fish_encounters %>% pivot_wider(
    names_from = station,
    values_from = seen
)

   fish Release I80_1 Lisbon Rstr Base_TD BCE BCW BCE2 BCW2 MAE MAW
1  4842 1       1      1      1    1       1   1   1    1    1   1
2  4843 1       1      1      1    1       1   1   1    1    1   1
3  4844 1       1      1      1    1       1   1   1    1    1   1
4  4845 1       1      1      1    1      NA  NA  NA   NA   NA  NA
5  4847 1       1      1     NA   NA      NA  NA  NA   NA   NA  NA
6  4848 1       1      1      1   NA      NA  NA  NA   NA   NA  NA
7  4849 1       1     NA     NA   NA      NA  NA  NA   NA   NA  NA
8  4850 1       1     NA      1    1       1   1  NA   NA   NA  NA
9  4851 1       1     NA     NA   NA      NA  NA  NA   NA   NA  NA
10 4854 1       1     NA     NA   NA      NA  NA  NA   NA   NA  NA
11 4855 1       1      1      1    1      NA  NA  NA   NA   NA  NA
12 4857 1       1      1      1    1       1   1   1    1   NA  NA
13 4858 1       1      1      1    1       1   1   1    1    1   1
14 4859 1       1      1      1    1      NA  NA  NA   NA   NA  NA
15 4861 1       1      1      1    1       1   1   1    1    1   1
16 4862 1       1      1      1    1       1   1   1    1   NA  NA
17 4863 1       1     NA     NA   NA      NA  NA  NA   NA   NA  NA
18 4864 1       1     NA     NA   NA      NA  NA  NA   NA   NA  NA
19 4865 1       1      1     NA   NA      NA  NA  NA   NA   NA  NA

This dataset only records when a fish was detected by the station - it doesn’t record when it wasn’t detected (this is common with this type of data). That means the output data is filled with NAs. However, in this case we know that the absence of a record means that the fish was not seen, so we can ask `pivot_wider()` to fill these missing values in with zeros:

In [72]:
fish_encounters %>% pivot_wider(
    names_from = station,
    values_from = seen,
    values_fill = 0
)

   fish Release I80_1 Lisbon Rstr Base_TD BCE BCW BCE2 BCW2 MAE MAW
1  4842 1       1     1      1    1       1   1   1    1    1   1
2  4843 1       1     1      1    1       1   1   1    1    1   1
3  4844 1       1     1      1    1       1   1   1    1    1   1
4  4845 1       1     1      1    1       0   0   0    0    0   0
5  4847 1       1     1      0    0       0   0   0    0    0   0
6  4848 1       1     1      1    0       0   0   0    0    0   0
7  4849 1       1     0      0    0       0   0   0    0    0   0
8  4850 1       1     0      1    1       1   1   0    0    0   0
9  4851 1       1     0      0    0       0   0   0    0    0   0
10 4854 1       1     0      0    0       0   0   0    0    0   0
11 4855 1       1     1      1    1       0   0   0    0    0   0
12 4857 1       1     1      1    1       1   1   1    1    0   0
13 4858 1       1     1      1    1       1   1   1    1    1   1
14 4859 1       1     1      1    1       0   0   0    0    0   0
15 4861 1       1     1      1    1       1   1   1    1    1   1
16 4862 1       1     1      1    1       1   1   1    1    0   0
17 4863 1       1     0      0    0       0   0   0    0    0   0
18 4864 1       1     0      0    0       0   0   0    0    0   0
19 4865 1       1     1      0    0       0   0   0    0    0   0

# Aggregation

You can also use `pivot_wider()` to perform simple aggregation. For example, take the warpbreaks dataset built in to base R (converted to a tibble for the better print method):

In [78]:
warpbreaks %>% head(20)

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M
11 21     A    M
12 29     A    M
13 17     A    M
14 12     A    M
15 18     A    M
16 35     A    M
17 30     A    M
18 36     A    M
19 36     A    H
20 21     A    H

This is a designed experiment with nine replicates for every combination of wool (A and B) and tension (L, M, H):

In [79]:
warpbreaks %>% count(wool, tension)

  wool tension n
1 A    L       9
2 A    M       9
3 A    H       9
4 B    L       9
5 B    M       9
6 B    H       9

What happens if we attempt to pivot the levels of `wool` into the columns?

In [80]:
warpbreaks %>% pivot_wider(names_from = wool, values_from = breaks)

Warning message:
"Values are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = length` to identify where the duplicates arise
* Use `values_fn = {summary_fun}` to summarise duplicates"

  tension A                                  B
1 L       26, 30, 54, 25, 70, 52, 51, 26, 67 27, 14, 29, 19, 29, 31, 41, 20, 44
2 M       18, 21, 29, 17, 12, 18, 35, 30, 36 42, 26, 19, 16, 39, 28, 21, 39, 29
3 H       36, 21, 24, 18, 10, 43, 28, 15, 26 20, 21, 24, 17, 13, 15, 15, 16, 28

In [82]:
#Take the mean of each cell of the dataframe above
warpbreaks %>% pivot_wider(
    names_from = wool, 
    values_from = breaks,
    values_fn = list(breaks = mean)
)

  tension A        B
1 L       44.55556 28.22222
2 M       24.00000 28.77778
3 H       24.55556 18.77778

### Generate column name from multiple variables

In [83]:
production <- expand_grid(
    product = c("A", "B"),
    country = c("AI", "EI"),
    year = 2000:2014
  ) %>%
  filter((product == "A" & country == "AI") | product == "B") %>%
  mutate(production = rnorm(nrow(.)))

production

   product country year production
1  A       AI      2000  0.72368831
2  A       AI      2001  0.11913989
3  A       AI      2002 -0.20615286
4  A       AI      2003 -0.11186367
5  A       AI      2004 -0.44791115
6  A       AI      2005 -0.56234109
7  A       AI      2006 -0.74534835
8  A       AI      2007  0.80040114
9  A       AI      2008 -0.64437748
10 A       AI      2009 -0.16505162
11 A       AI      2010  0.13491843
12 A       AI      2011 -0.67344096
13 A       AI      2012 -0.50381678
14 A       AI      2013  0.14511413
15 A       AI      2014 -0.13938577
16 B       AI      2000 -1.56452571
17 B       AI      2001  1.04990847
18 B       AI      2002  1.64870923
19 B       AI      2003  0.32817441
20 B       AI      2004 -0.04553985
21 B       AI      2005  0.01912910
22 B       AI      2006 -2.70788044
23 B       AI      2007  2.30098634
24 B       AI      2008  2.75382375
25 B       AI      2009 -0.08501352
26 B       AI      2010  2.12272487
27 B       AI      2011  0.60762711
28 B       AI      2012 -0.14269482
29 B       AI      2013 -1.67292215
30 B       AI      2014 -0.19528908
31 B       EI      2000  0.92287470
32 B       EI      2001 -0.95885012
33 B       EI      2002  0.90391624
34 B       EI      2003 -0.70377888
35 B       EI      2004  0.06608078
36 B       EI      2005 -0.33946197
37 B       EI      2006  0.53660897
38 B       EI      2007 -2.04866049
39 B       EI      2008 -0.06843437
40 B       EI      2009  0.98061507
41 B       EI      2010  0.55515467
42 B       EI      2011  0.33834179
43 B       EI      2012  0.72343953
44 B       EI      2013  1.35723605
45 B       EI      2014  0.34666981

We want to widen the data so we have one column for each combination of product and country. The key is to specify multiple variables for `names_from`:

In [84]:
production %>% pivot_wider(
  names_from = c(product, country),
  values_from = production
)

   year A_AI       B_AI        B_EI
1  2000  0.7236883 -1.56452571  0.92287470
2  2001  0.1191399  1.04990847 -0.95885012
3  2002 -0.2061529  1.64870923  0.90391624
4  2003 -0.1118637  0.32817441 -0.70377888
5  2004 -0.4479111 -0.04553985  0.06608078
6  2005 -0.5623411  0.01912910 -0.33946197
7  2006 -0.7453483 -2.70788044  0.53660897
8  2007  0.8004011  2.30098634 -2.04866049
9  2008 -0.6443775  2.75382375 -0.06843437
10 2009 -0.1650516 -0.08501352  0.98061507
11 2010  0.1349184  2.12272487  0.55515467
12 2011 -0.6734410  0.60762711  0.33834179
13 2012 -0.5038168 -0.14269482  0.72343953
14 2013  0.1451141 -1.67292215  1.35723605
15 2014 -0.1393858 -0.19528908  0.34666981

When either names_from or values_from select multiple variables, you can control how the column names in the output constructed with `names_sep` and `names_prefix`, or the workhorse `names_glue`:

In [85]:
production %>% pivot_wider(
    names_from = c(product, country),
    values_from = production,
    names_sep = '-',
    names_prefix = 'product.'
)

   year product.A-AI product.B-AI product.B-EI
1  2000  0.7236883   -1.56452571   0.92287470
2  2001  0.1191399    1.04990847  -0.95885012
3  2002 -0.2061529    1.64870923   0.90391624
4  2003 -0.1118637    0.32817441  -0.70377888
5  2004 -0.4479111   -0.04553985   0.06608078
6  2005 -0.5623411    0.01912910  -0.33946197
7  2006 -0.7453483   -2.70788044   0.53660897
8  2007  0.8004011    2.30098634  -2.04866049
9  2008 -0.6443775    2.75382375  -0.06843437
10 2009 -0.1650516   -0.08501352   0.98061507
11 2010  0.1349184    2.12272487   0.55515467
12 2011 -0.6734410    0.60762711   0.33834179
13 2012 -0.5038168   -0.14269482   0.72343953
14 2013  0.1451141   -1.67292215   1.35723605
15 2014 -0.1393858   -0.19528908   0.34666981

In [86]:
production %>% pivot_wider(
  names_from = c(product, country),
  values_from = production,
  names_glue = "prod_{product}_{country}"
)

   year prod_A_AI  prod_B_AI   prod_B_EI
1  2000  0.7236883 -1.56452571  0.92287470
2  2001  0.1191399  1.04990847 -0.95885012
3  2002 -0.2061529  1.64870923  0.90391624
4  2003 -0.1118637  0.32817441 -0.70377888
5  2004 -0.4479111 -0.04553985  0.06608078
6  2005 -0.5623411  0.01912910 -0.33946197
7  2006 -0.7453483 -2.70788044  0.53660897
8  2007  0.8004011  2.30098634 -2.04866049
9  2008 -0.6443775  2.75382375 -0.06843437
10 2009 -0.1650516 -0.08501352  0.98061507
11 2010  0.1349184  2.12272487  0.55515467
12 2011 -0.6734410  0.60762711  0.33834179
13 2012 -0.5038168 -0.14269482  0.72343953
14 2013  0.1451141 -1.67292215  1.35723605
15 2014 -0.1393858 -0.19528908  0.34666981

### Tidy cencus

The `us_rent_income` dataset contains information about median income and rent for each state in the US for 2017 (from the American Community Survey, retrieved with the tidycensus package).

In [88]:
us_rent_income %>% head(20)

   GEOID NAME                 variable estimate moe
1  01    Alabama              income   24476    136
2  01    Alabama              rent       747      3
3  02    Alaska               income   32940    508
4  02    Alaska               rent      1200     13
5  04    Arizona              income   27517    148
6  04    Arizona              rent       972      4
7  05    Arkansas             income   23789    165
8  05    Arkansas             rent       709      5
9  06    California           income   29454    109
10 06    California           rent      1358      3
11 08    Colorado             income   32401    109
12 08    Colorado             rent      1125      5
13 09    Connecticut          income   35326    195
14 09    Connecticut          rent      1123      5
15 10    Delaware             income   31560    247
16 10    Delaware             rent      1076     10
17 11    District of Columbia income   43198    681
18 11    District of Columbia rent      1424     17
19 12    Florida              income   25952     70
20 12    Florida              rent      1077      3

Here both `estimate` and `moe` are values columns, so we can supply them to `values_from`:

In [90]:
us_rent_income %>% pivot_wider(
    names_from = variable,
    values_from = c(estimate, moe)
) %>% head()

  GEOID NAME       estimate_income estimate_rent moe_income moe_rent
1 01    Alabama    24476            747          136         3
2 02    Alaska     32940           1200          508        13
3 04    Arizona    27517            972          148         4
4 05    Arkansas   23789            709          165         5
5 06    California 29454           1358          109         3
6 08    Colorado   32401           1125          109         5

### Contact list

In [91]:
contacts <- tribble(
  ~field, ~value,
  "name", "Jiena McLellan",
  "company", "Toyota",
  "name", "John Smith",
  "company", "google",
  "email", "john@google.com",
  "name", "Huxley Ratcliffe"
)

contacts

  field   value
1 name    Jiena McLellan
2 company Toyota
3 name    John Smith
4 company google
5 email   john@google.com
6 name    Huxley Ratcliffe

This is challenging because there’s no variable that identifies which observations belong together. We can fix this by noting that every contact starts with a name, so we can create a unique id by counting every time we see “name” as the field:

In [93]:
contacts <- contacts %>%
  mutate(
    person_id = cumsum(field == "name")
  )
contacts

  field   value            person_id
1 name    Jiena McLellan   1
2 company Toyota           1
3 name    John Smith       2
4 company google           2
5 email   john@google.com  2
6 name    Huxley Ratcliffe 3

In [94]:
contacts %>%
  pivot_wider(names_from = field, values_from = value)

  person_id name             company email
1 1         Jiena McLellan   Toyota  NA
2 2         John Smith       google  john@google.com
3 3         Huxley Ratcliffe NA      NA

# Longer then Wider

### World bank

In [96]:
world_bank_pop %>% head()

  country indicator   2000         2001         2002         2003
1 ABW     SP.URB.TOTL 4.244400e+04 4.304800e+04 4.367000e+04 4.424600e+04
2 ABW     SP.URB.GROW 1.182632e+00 1.413021e+00 1.434560e+00 1.310360e+00
3 ABW     SP.POP.TOTL 9.085300e+04 9.289800e+04 9.499200e+04 9.701700e+04
4 ABW     SP.POP.GROW 2.055027e+00 2.225930e+00 2.229056e+00 2.109354e+00
5 AFG     SP.URB.TOTL 4.436299e+06 4.648055e+06 4.892951e+06 5.155686e+06
6 AFG     SP.URB.GROW 3.912228e+00 4.662838e+00 5.134675e+00 5.230459e+00
  2004         2005         2006          2007          2008
1 4.466900e+04 4.488900e+04  4.488100e+04  4.468600e+04  4.437500e+04
2 9.514777e-01 4.913027e-01 -1.782333e-02 -4.354289e-01 -6.984006e-01
3 9.873700e+04 1.000310e+05  1.008320e+05  1.012200e+05  1.013530e+05
4 1.757353e+00 1.302039e+00  7.975628e-01  3.840600e-01  1.313107e-01
5 5.426770e+06 5.691823e+06  5.931413e+06  6.151939e+06  6.364968e+06
6 5.124393e+00 4.768647e+00  4.123188e+00  3.650485e+00  3.404189e+00
  2009          2010          2011         2012         2013
1  4.405200e+04  4.377800e+04 4.382200e+04 4.406400e+04 4.436000e+04
2 -7.305493e-01 -6.239346e-01 1.004566e-01 5.507148e-01 6.695040e-01
3  1.014530e+05  1.016690e+05 1.020530e+05 1.025770e+05 1.031870e+05
4  9.861642e-02  2.126801e-01 3.769848e-01 5.121450e-01 5.929140e-01
5  6.588859e+06  6.837008e+06 7.114615e+06 7.416385e+06 7.733964e+06
6  3.457099e+00  3.697002e+00 3.980091e+00 4.154062e+00 4.192980e+00
  2014         2015         2016         2017
1 4.467400e+04 4.497900e+04 4.527500e+04 4.557200e+04
2 7.053514e-01 6.804037e-01 6.559290e-01 6.538489e-01
3 1.037950e+05 1.043410e+05 1.048220e+05 1.052640e+05
4 5.874924e-01 5.246582e-01 4.599292e-01 4.207807e-01
5 8.054214e+06 8.367663e+06 8.670939e+06 8.971345e+06
6 4.057389e+00 3.817920e+00 3.560246e+00 3.405852e+00

My goal is to produce a tidy dataset where each variable is in a column. It’s not obvious exactly what steps are needed yet, but I’ll start with the most obvious problem: year is spread across multiple columns.

In [102]:
pop2 <- world_bank_pop %>% pivot_longer(
    cols = `2000`:`2017`,
    names_to = 'year',
    values_to = 'value'
)

pop2 %>% head(20)

   country indicator   year value
1  ABW     SP.URB.TOTL 2000 42444.000000
2  ABW     SP.URB.TOTL 2001 43048.000000
3  ABW     SP.URB.TOTL 2002 43670.000000
4  ABW     SP.URB.TOTL 2003 44246.000000
5  ABW     SP.URB.TOTL 2004 44669.000000
6  ABW     SP.URB.TOTL 2005 44889.000000
7  ABW     SP.URB.TOTL 2006 44881.000000
8  ABW     SP.URB.TOTL 2007 44686.000000
9  ABW     SP.URB.TOTL 2008 44375.000000
10 ABW     SP.URB.TOTL 2009 44052.000000
11 ABW     SP.URB.TOTL 2010 43778.000000
12 ABW     SP.URB.TOTL 2011 43822.000000
13 ABW     SP.URB.TOTL 2012 44064.000000
14 ABW     SP.URB.TOTL 2013 44360.000000
15 ABW     SP.URB.TOTL 2014 44674.000000
16 ABW     SP.URB.TOTL 2015 44979.000000
17 ABW     SP.URB.TOTL 2016 45275.000000
18 ABW     SP.URB.TOTL 2017 45572.000000
19 ABW     SP.URB.GROW 2000     1.182632
20 ABW     SP.URB.GROW 2001     1.413021

Next we need to consider the `indicator` variable:

In [105]:
pop2 %>% count(indicator)

  indicator   n
1 SP.POP.GROW 4752
2 SP.POP.TOTL 4752
3 SP.URB.GROW 4752
4 SP.URB.TOTL 4752

Here SP.POP.GROW is population growth, SP.POP.TOTL is total population, and SP.URB.* are the same but only for urban areas. Let’s split this up into two variables: area (total or urban) and the actual variable (population or growth):

In [106]:
pop3 <- pop2 %>%
  separate(indicator, c(NA, "area", "variable"))
pop3

      country area variable year value
1     ABW     URB  TOTL     2000  4.244400e+04
2     ABW     URB  TOTL     2001  4.304800e+04
3     ABW     URB  TOTL     2002  4.367000e+04
4     ABW     URB  TOTL     2003  4.424600e+04
5     ABW     URB  TOTL     2004  4.466900e+04
6     ABW     URB  TOTL     2005  4.488900e+04
7     ABW     URB  TOTL     2006  4.488100e+04
8     ABW     URB  TOTL     2007  4.468600e+04
9     ABW     URB  TOTL     2008  4.437500e+04
10    ABW     URB  TOTL     2009  4.405200e+04
11    ABW     URB  TOTL     2010  4.377800e+04
12    ABW     URB  TOTL     2011  4.382200e+04
13    ABW     URB  TOTL     2012  4.406400e+04
14    ABW     URB  TOTL     2013  4.436000e+04
15    ABW     URB  TOTL     2014  4.467400e+04
16    ABW     URB  TOTL     2015  4.497900e+04
17    ABW     URB  TOTL     2016  4.527500e+04
18    ABW     URB  TOTL     2017  4.557200e+04
19    ABW     URB  GROW     2000  1.182632e+00
20    ABW     URB  GROW     2001  1.413021e+00
21    ABW     URB  GROW     2002  1.434560e+00
22    ABW     URB  GROW     2003  1.310360e+00
23    ABW     URB  GROW     2004  9.514777e-01
24    ABW     URB  GROW     2005  4.913027e-01
25    ABW     URB  GROW     2006 -1.782333e-02
26    ABW     URB  GROW     2007 -4.354289e-01
27    ABW     URB  GROW     2008 -6.984006e-01
28    ABW     URB  GROW     2009 -7.305493e-01
29    ABW     URB  GROW     2010 -6.239346e-01
30    ABW     URB  GROW     2011  1.004566e-01
...   ...     ...  ...      ...  ...
18979 ZWE     POP  TOTL     2006 1.312427e+07
18980 ZWE     POP  TOTL     2007 1.332991e+07
18981 ZWE     POP  TOTL     2008 1.355847e+07
18982 ZWE     POP  TOTL     2009 1.381060e+07
18983 ZWE     POP  TOTL     2010 1.408632e+07
18984 ZWE     POP  TOTL     2011 1.438665e+07
18985 ZWE     POP  TOTL     2012 1.471083e+07
18986 ZWE     POP  TOTL     2013 1.505451e+07
18987 ZWE     POP  TOTL     2014 1.541168e+07
18988 ZWE     POP  TOTL     2015 1.577745e+07
18989 ZWE     POP  TOTL     2016 1.615036e+07
18990 ZWE     POP  TOTL     2017 1.652990e+07
18991 ZWE     POP  GROW     2000 1.298782e+00
18992 ZWE     POP  GROW     2001 1.170597e+00
18993 ZWE     POP  GROW     2002 1.080653e+00
18994 ZWE     POP  GROW     2003 1.061280e+00
18995 ZWE     POP  GROW     2004 1.130323e+00
18996 ZWE     POP  GROW     2005 1.263909e+00
18997 ZWE     POP  GROW     2006 1.413720e+00
18998 ZWE     POP  GROW     2007 1.554735e+00
18999 ZWE     POP  GROW     2008 1.700106e+00
19000 ZWE     POP  GROW     2009 1.842497e+00
19001 ZWE     POP  GROW     2010 1.976756e+00
19002 ZWE     POP  GROW     2011 2.109672e+00
19003 ZWE     POP  GROW     2012 2.228306e+00
19004 ZWE     POP  GROW     2013 2.309366e+00
19005 ZWE     POP  GROW     2014 2.344799e+00
19006 ZWE     POP  GROW     2015 2.345643e+00
19007 ZWE     POP  GROW     2016 2.336070e+00
19008 ZWE     POP  GROW     2017 2.322864e+00

Now we can complete the tidying by pivoting variable and value to make `TOTL` and `GROW` columns:

In [107]:
pop3 %>%
  pivot_wider(names_from = variable, values_from = value)

     country area year TOTL     GROW
1    ABW     URB  2000  42444    1.18263237
2    ABW     URB  2001  43048    1.41302122
3    ABW     URB  2002  43670    1.43455953
4    ABW     URB  2003  44246    1.31036044
5    ABW     URB  2004  44669    0.95147768
6    ABW     URB  2005  44889    0.49130271
7    ABW     URB  2006  44881   -0.01782333
8    ABW     URB  2007  44686   -0.43542891
9    ABW     URB  2008  44375   -0.69840057
10   ABW     URB  2009  44052   -0.73054935
11   ABW     URB  2010  43778   -0.62393462
12   ABW     URB  2011  43822    0.10045663
13   ABW     URB  2012  44064    0.55071482
14   ABW     URB  2013  44360    0.66950399
15   ABW     URB  2014  44674    0.70535144
16   ABW     URB  2015  44979    0.68040373
17   ABW     URB  2016  45275    0.65592896
18   ABW     URB  2017  45572    0.65384891
19   ABW     POP  2000  90853    2.05502678
20   ABW     POP  2001  92898    2.22593013
21   ABW     POP  2002  94992    2.22905605
22   ABW     POP  2003  97017    2.10935434
23   ABW     POP  2004  98737    1.75735287
24   ABW     POP  2005 100031    1.30203884
25   ABW     POP  2006 100832    0.79756276
26   ABW     POP  2007 101220    0.38406002
27   ABW     POP  2008 101353    0.13131071
28   ABW     POP  2009 101453    0.09861642
29   ABW     POP  2010 101669    0.21268014
30   ABW     POP  2011 102053    0.37698477
...  ...     ...  ...  ...      ...
9475 ZWE     URB  2006  4452539 0.8728304
9476 ZWE     URB  2007  4497911 1.0138572
9477 ZWE     URB  2008  4550222 1.1562956
9478 ZWE     URB  2009  4609702 1.2987190
9479 ZWE     URB  2010  4676094 1.4299933
9480 ZWE     URB  2011  4749752 1.5629260
9481 ZWE     URB  2012  4830153 1.6785738
9482 ZWE     URB  2013  4915898 1.7596299
9483 ZWE     URB  2014  5009411 1.8843900
9484 ZWE     URB  2015  5109528 1.9788689
9485 ZWE     URB  2016  5215921 2.0608647
9486 ZWE     URB  2017  5328745 2.1400072
9487 ZWE     POP  2000 12222251 1.2987820
9488 ZWE     POP  2001 12366165 1.1705971
9489 ZWE     POP  2002 12500525 1.0806529
9490 ZWE     POP  2003 12633897 1.0612796
9491 ZWE     POP  2004 12777511 1.1303233
9492 ZWE     POP  2005 12940032 1.2639089
9493 ZWE     POP  2006 13124267 1.4137197
9494 ZWE     POP  2007 13329909 1.5547348
9495 ZWE     POP  2008 13558469 1.7001063
9496 ZWE     POP  2009 13810599 1.8424970
9497 ZWE     POP  2010 14086317 1.9767560
9498 ZWE     POP  2011 14386649 2.1096723
9499 ZWE     POP  2012 14710826 2.2283062
9500 ZWE     POP  2013 15054506 2.3093663
9501 ZWE     POP  2014 15411675 2.3447991
9502 ZWE     POP  2015 15777451 2.3456430
9503 ZWE     POP  2016 16150362 2.3360695
9504 ZWE     POP  2017 16529904 2.3228640

# Multi-Choice

In [108]:
multi <- tribble(
  ~id, ~choice1, ~choice2, ~choice3,
  1, "A", "B", "C",
  2, "C", "B",  NA,
  3, "D",  NA,  NA,
  4, "B", "D",  NA
)

multi

  id choice1 choice2 choice3
1 1  A       B       C
2 2  C       B       NA
3 3  D       NA      NA
4 4  B       D       NA

But the actual order isn’t important, and you’d prefer to have the individual questions in the columns. You can achieve the desired transformation in two steps. First, you make the data longer, eliminating the explcit NAs, and adding a column to indicate that this choice was chosen:

In [109]:
multi2 <- multi %>%
  pivot_longer(!id, values_drop_na = TRUE) %>%
  mutate(checked = TRUE)
multi2

  id name    value checked
1 1  choice1 A     TRUE
2 1  choice2 B     TRUE
3 1  choice3 C     TRUE
4 2  choice1 C     TRUE
5 2  choice2 B     TRUE
6 3  choice1 D     TRUE
7 4  choice1 B     TRUE
8 4  choice2 D     TRUE

Then you make the data wider, filling in the missing observations with FALSE:

In [111]:
multi2 %>% pivot_wider(
    id_cols = id,
    names_from = value,
    values_from = checked,
    values_fill = F
)

  id A     B     C     D
1 1   TRUE  TRUE  TRUE FALSE
2 2  FALSE  TRUE  TRUE FALSE
3 3  FALSE FALSE FALSE  TRUE
4 4  FALSE  TRUE FALSE  TRUE

# Manual Spec

### Longer

 Now pivotting happens in two steps: we first create a spec object (using **`build_longer_spec()`**) then use that to describe the pivotting operation:

In [3]:
relig_income %>% head()

  religion           <$10k $10-20k $20-30k $30-40k $40-50k $50-75k $75-100k
1 Agnostic            27    34       60     81      76      137    122
2 Atheist             12    27       37     52      35       70     73
3 Buddhist            27    21       30     34      33       58     62
4 Catholic           418   617      732    670     638     1116    949
5 Don’t know/refused  15    14       15     11      10       35     21
6 Evangelical Prot   575   869     1064    982     881     1486    949
  $100-150k >150k Don't know/refused
1 109        84     96
2  59        74     76
3  39        53     54
4 792       633   1489
5  17        18    116
6 723       414   1529

Spec object:
* **`.name`** gives the name of the column.
* **`.value`** gives the name of the column that the values in the cells will go into.

In [6]:
#Spec object
relig_income_spec <- relig_income %>% build_longer_spec(
    cols = !religion,
    names_to = 'income',
    values_to = 'count'
)

relig_income_spec

   .name              .value income
1  <$10k              count  <$10k
2  $10-20k            count  $10-20k
3  $20-30k            count  $20-30k
4  $30-40k            count  $30-40k
5  $40-50k            count  $40-50k
6  $50-75k            count  $50-75k
7  $75-100k           count  $75-100k
8  $100-150k          count  $100-150k
9  >150k              count  >150k
10 Don't know/refused count  Don't know/refused

In [9]:
#Use spec object
relig_income %>% pivot_longer_spec(relig_income_spec) %>% head(20)

   religion income             count
1  Agnostic <$10k               27
2  Agnostic $10-20k             34
3  Agnostic $20-30k             60
4  Agnostic $30-40k             81
5  Agnostic $40-50k             76
6  Agnostic $50-75k            137
7  Agnostic $75-100k           122
8  Agnostic $100-150k          109
9  Agnostic >150k               84
10 Agnostic Don't know/refused  96
11 Atheist  <$10k               12
12 Atheist  $10-20k             27
13 Atheist  $20-30k             37
14 Atheist  $30-40k             52
15 Atheist  $40-50k             35
16 Atheist  $50-75k             70
17 Atheist  $75-100k            73
18 Atheist  $100-150k           59
19 Atheist  >150k               74
20 Atheist  Don't know/refused  76

### Wider

Below we widen `us_rent_income` with **`pivot_wider()`**. The result is ok, but I think it could be improved:

In [10]:
us_rent_income %>% head()

  GEOID NAME    variable estimate moe
1 01    Alabama income   24476    136
2 01    Alabama rent       747      3
3 02    Alaska  income   32940    508
4 02    Alaska  rent      1200     13
5 04    Arizona income   27517    148
6 04    Arizona rent       972      4

In [11]:
us_rent_income %>% pivot_wider(
    names_from = variable,
    values_from =c(estimate, moe)
) %>% head()

  GEOID NAME       estimate_income estimate_rent moe_income moe_rent
1 01    Alabama    24476            747          136         3
2 02    Alaska     32940           1200          508        13
3 04    Arizona    27517            972          148         4
4 05    Arkansas   23789            709          165         5
5 06    California 29454           1358          109         3
6 08    Colorado   32401           1125          109         5

I think it would be better to have columns `income`, `rent`, `income_moe`, and `rent_moe`, which we can achieve with a manual spec. The current spec looks like this:

In [13]:
spec1 <- us_rent_income %>% build_wider_spec(
    names_from = variable,
    values_from = c(estimate, moe)
)

spec1

  .name           .value   variable
1 estimate_income estimate income
2 estimate_rent   estimate rent
3 moe_income      moe      income
4 moe_rent        moe      rent

For this case, we mutate spec to carefully construct the column names:

In [16]:
spec2 <- spec1 %>% mutate(
    .name = paste0(variable, ifelse(.value == 'moe', '_moe', ''))
)

spec2

  .name      .value   variable
1 income     estimate income
2 rent       estimate rent
3 income_moe moe      income
4 rent_moe   moe      rent

In [17]:
us_rent_income %>% pivot_wider_spec(spec2) %>% head()

  GEOID NAME       income rent income_moe rent_moe
1 01    Alabama    24476   747 136         3
2 02    Alaska     32940  1200 508        13
3 04    Arizona    27517   972 148         4
4 05    Arkansas   23789   709 165         5
5 06    California 29454  1358 109         3
6 08    Colorado   32401  1125 109         5

### By hand