In [1]:
import pandas as pd
import numpy as np
import os
os.chdir(r'C:\Users\dell\PycharmProjects\MachineLearning\Pandas\datasets')

There are 2 kinds of sorting in Pandas
<ul>
<li>by index</li>
<li>by actual value</li>
</ul>

# Sort Index

```python
pokemon.sort_index(
    axis=0,
    level=None,
    ascending=True,
    inplace=False,
    kind='quicksort',
    na_position='last',
    sort_remaining=True,
    by=None,
)
```

In [2]:
np.random.seed(205)
df = pd.DataFrame(np.random.randint(5,10, (3,3)), index = ['Google', 'Apple', 'Samsung'], columns = ['Phone', 'Computer', 'Glass'])
#NOTE: pay a very close attention to the keyword: axis
#sort by row labels: df.sort_index(axis = 0)
#sort by column labels: df.sort_index(axis = 1)
df

         Phone  Computer  Glass
Google       7         9      5
Apple        9         5      9
Samsung      5         8      8

sort row index:

In [3]:
order_by_row = df.sort_index(axis = 0)
order_by_row

         Phone  Computer  Glass
Apple        9         5      9
Google       7         9      5
Samsung      5         8      8

sort column labels:

In [4]:


#Order by column label:

df.sort_index(axis = 1, inplace = True, ascending = False)
df

         Phone  Glass  Computer
Google       7      5         9
Apple        9      9         5
Samsung      5      8         8

<hr>

In [9]:
housing = pd.read_csv('./housing.csv')
housing.head(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY

In [12]:
housing.sort_index(axis = 1, ascending = False, kind = 'heapsort').head(3)

,total_rooms,total_bedrooms,population,ocean_proximity,median_income,median_house_value,longitude,latitude,housing_median_age,households
0,880.0,129.0,322.0,NEAR BAY,8.3252,452600.0,-122.23,37.88,41.0,126.0
1,7099.0,1106.0,2401.0,NEAR BAY,8.3014,358500.0,-122.22,37.86,21.0,1138.0
2,1467.0,190.0,496.0,NEAR BAY,7.2574,352100.0,-122.24,37.85,52.0,177.0

# Sort values

```python
pokemon.sort_values(
    by,
    axis=0,
    ascending=True,
    inplace=False,
    kind='quicksort',
    na_position='last',
)
```

sort based on values of multiple columns:

In [6]:
pokemon = pd.read_csv('./pokemon.csv')

#order by Attack, Defense, HP desc (SQL)
#is equivalent to: df.sort_values(by = ['Attack', 'Defense', 'HP'], ascending = False)
order = pokemon.sort_values(by = ['Attack', 'Defense', 'HP'], ascending = False, kind = 'heapsort')
order[['Name', 'Attack', 'Defense', 'HP', 'Legendary']]

                        Name  Attack  Defense   HP  Legendary
163      MewtwoMega Mewtwo X     190      100  106       True
232  HeracrossMega Heracross     185      115   80      False
424    GroudonPrimal Groudon     180      160  100       True
426    RayquazaMega Rayquaza     180      100  105       True
429       DeoxysAttack Forme     180       20   50       True
494    GarchompMega Garchomp     170      115  108      False
711       KyuremBlack Kyurem     170      100  125       True
527      GalladeMega Gallade     165       95   68      False
387      BanetteMega Banette     165       75   64      False
454                Rampardos     165       60   97      False
268  TyranitarMega Tyranitar     164      150  100      False
543                Regigigas     160      110  110       True
796      DiancieMega Diancie     160      110   50       True
313                  Slaking     160      100  150      False
279    BlazikenMega Blaziken     160       80   80      False
798       HoopaHoopa Unbound     160       60   80       True
137        PinsirMega Pinsir     155      120   65      False
141    GyaradosMega Gyarados     155      109   95      False
423                  Groudon     150      140  100       True
229        ScizorMega Scizor     150      140   70      False
707                   Zekrom     150      120  100       True
283    SwampertMega Swampert     150      110  100      False
425                 Rayquaza     150       90  105       True
422      KyogrePrimal Kyogre     150       90  100       True
164      MewtwoMega Mewtwo Y     150       70  106       True
393          AbsolMega Absol     150       60   65      False
750     AegislashBlade Forme     150       50   60      False
428       DeoxysNormal Forme     150       50   50       True
19     BeedrillMega Beedrill     150       40   65      False
673                  Haxorus     147       90   76      False
..                       ...     ...      ...  ...        ...
301                  Wingull      30       30   40      False
206                  Sunkern      30       30   30      False
188                Igglybuff      30       15   90      False
257                 Smoochum      30       15   45      False
457                    Burmy      29       45   40      False
606                 Cottonee      27       60   40      False
17                    Kakuna      25       50   45      False
576                    Munna      25       45   76      False
487                 Mime Jr.      25       45   20      False
446                Kricketot      25       41   37      False
356                   Spoink      25       35   60      False
187                   Cleffa      25       28   50      False
303                    Ralts      25       25   28      False
484                  Bronzor      24       86   57      False
394                   Wynaut      23       48   95      False
733                   Spewpa      22       60   45      False
189                   Togepi      20       65   35      False
14                   Metapod      20       55   50      False
198                   Marill      20       50   70      False
508                  Mantyke      20       50   45      False
322                  Azurill      20       40   50      False
254                 Smeargle      20       35   55      False
179                   Ledyba      20       30   40      False
68                      Abra      20       15   25      False
381                   Feebas      15       20   20      False
230                  Shuckle      10      230   20      False
139                 Magikarp      10       55   20      False
261                  Blissey      10       10  255      False
121                  Chansey       5        5  250      False
488                  Happiny       5        5  100      False

[800 rows x 5 columns]

In [18]:
sort based on value of 1 column:

SyntaxError: invalid syntax (<ipython-input-18-dd15f2107b9a>, line 1)

In [17]:
#let's order pokemon by its speed descending
pokemon.sort_values(by = 'Speed', ascending = False, kind = 'mergesort', axis = 0)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
431,386,DeoxysSpeed Forme,Psychic,NaN,600,50,95,90,95,90,180,3,True
315,291,Ninjask,Bug,Flying,456,61,90,45,50,50,160,3,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
109,101,Electrode,Electric,NaN,480,60,50,70,80,80,140,1,False
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
339,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False
476,428,LopunnyMega Lopunny,Normal,Fighting,580,65,136,94,54,96,135,4,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
146,135,Jolteon,Electric,NaN,525,65,65,60,110,95,130,1,False
153,142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,False
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
183,169,Crobat,Poison,Flying,535,85,90,80,70,80,130,2,False
716,648,MeloettaPirouette Forme,Normal,Fighting,600,100,128,90,77,77,128,5,False
551,492,ShayminSky Forme,Grass,Flying,600,100,103,75,120,75,127,4,True
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False
300,277,Swellow,Normal,Flying,430,60,85,60,50,50,125,3,False
512,461,Weavile,Dark,Ice,510,70,120,65,45,85,125,4,False
549,491,Darkrai,Dark,NaN,600,70,90,90,135,90,125,4,True
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False
726,658,Greninja,Water,Dark,530,72,95,67,103,71,122,6,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
703,641,TornadusTherian Forme,Flying,NaN,580,79,100,80,110,90,121,5,True
56,51,Dugtrio,Ground,NaN,405,35,80,50,50,70,120,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,564,Tirtouga,Water,Rock,355,54,78,103,53,45,22,5,False
44,39,Jigglypuff,Normal,Fairy,270,115,45,20,45,25,20,1,False
80,74,Geodude,Rock,Ground,300,40,80,100,30,30,20,1,False
175,161,Sentret,Normal,NaN,215,35,46,34,35,45,20,2,False
189,175,Togepi,Fairy,NaN,245,35,20,65,40,65,20,2,False
236,218,Slugma,Fire,NaN,250,40,40,40,70,40,20,2,False
288,265,Wurmple,Bug,NaN,195,45,45,35,20,30,20,3,False
322,298,Azurill,Normal,Fairy,190,50,20,40,20,40,20,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,470,70,85,140,85,70,20,3,False
584,525,Boldore,Rock,NaN,390,70,105,105,50,40,20,5,False
638,577,Solosis,Psychic,NaN,290,45,30,40,105,50,20,5,False
650,589,Escavalier,Bug,Steel,495,70,135,105,60,105,20,5,False
659,598,Ferrothorn,Grass,Steel,489,74,94,131,54,116,20,5,False
668,607,Litwick,Ghost,Fire,275,50,30,55,65,55,20,5,False
85,79,Slowpoke,Water,Psychic,315,90,65,65,40,40,15,1,False
187,173,Cleffa,Fairy,NaN,218,50,25,28,45,55,15,2,False
188,174,Igglybuff,Normal,Fairy,210,90,30,15,40,20,15,2,False
209,194,Wooper,Water,Ground,210,55,45,45,25,25,15,2,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
289,266,Silcoon,Bug,NaN,205,50,35,55,25,25,15,3,False
291,268,Cascoon,Bug,NaN,205,50,35,55,25,25,15,3,False
583,524,Roggenrola,Rock,NaN,280,55,75,85,25,25,15,5,False
651,590,Foongus,Grass,Poison,294,69,55,45,55,55,15,5,False
359,328,Trapinch,Ground,NaN,290,45,100,45,45,45,10,3,False
486,438,Bonsly,Rock,NaN,290,50,80,95,10,45,10,4,False
658,597,Ferroseed,Grass,Steel,305,44,50,91,24,86,10,5,False
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
495,446,Munchlax,Normal,NaN,390,135,85,40,40,85,5,4,False

In [20]:
data = [
    [30, 'VN Champions', 56971],
    [35, 'Dirilis', 58930],
    [33, 'VN Champions', 57131]
]
TF = pd.DataFrame(data, index = ['VN Pikachu', 'ARMAGEDON', 'bac giang vn'], columns = ['level', 'clan', 'average damage']).T
TF

                  VN Pikachu ARMAGEDON  bac giang vn
level                     30        35            33
clan            VN Champions   Dirilis  VN Champions
average damage         56971     58930         57131

In [23]:
#let's sort columns based on the value of row average damage desc inplace
TF.sort_values(axis = 1, by = 'average damage', ascending = False, kind = 'quicksort')

               ARMAGEDON  bac giang vn    VN Pikachu
level                 35            33            30
clan             Dirilis  VN Champions  VN Champions
average damage     58930         57131         56971